### ISSUE TITLE
Homepage - Adding Header Stylings

### ISSUE THREAD

**Issue by bonnyg-Abt** [abtassociates/eva#122]
- Recommend providing header stylings for "Upload Hashed CSV zip file" and "HMIS CSV Export File Structure Analysis" to visually group them together 
 (Similar to what "Organization-Level" has - this helps the user easily notice what section changed and will change when a new file is uploaded)

**Comment by alex-silverman** [comment]
I like this layout, even if the bottoms of the boxes don't align:



![Image](https://user-images.githubusercontent.com/3285721/210851817-1a558025-0d6d-44a4-802e-2fa517798a12.png)

**Comment by alex-silverman** [comment]
I'm wondering if having it this way is still preferable to the current way, even if the boxes aren't the same height. It's still dashboard-y. And making them the same height is challening because the sizes of each change dynamically due to their contents.

**Comment by kiadso** [comment]
We decided to group them into their own tab- thank you for the feedback! (Will be pushed in a later version.)
