### ISSUE TITLE
View Client Counts - Date Ranges

### ISSUE THREAD

**Issue by bonnyg-Abt** [abtassociates/eva#123]
- No constraints on data range component and no error labels to indicate what the error is (Placed date 02/14/3100 - 12/14/2022 with no warning that this is erroneous)

**Comment by kiadso** [comment]
- add max date to updateDateRangeInput in Server.R
- add require for end date after start date

**Comment by kiadso** [comment]
Hi Bonny,
Thank you for the input, we are working on this!

**Comment by kiadso** [comment]
fixed
