### ISSUE TITLE
Assess Data Quality - Check PDDEs --> Disabled Filters

### ISSUE THREAD

**Issue by bonnyg-Abt** [abtassociates/eva#125]
- Type filter is disabled. Nothing to signify that "Error" will be the only type available and therefore filtering is not applicable -- add more information to the hover tooltip to tell this to the user. 
- Would this column filter be needed if this section will only show Type: Errors to the users?

**Comment by kiadso** [comment]
Thank you @bonnyg-Abt! Much appreciated! We have an edit in the queue that should make this less confusing.
