### ISSUE TITLE
App crash mimics a session timeout

### ISSUE THREAD

**Issue by kiadso** [abtassociates/eva#164]
**Describe the bug**
Whenever at least one user navigates to Eva, they immediately see the new timeout screen. 

**Screenshots**
forthcoming

**Additional context**
working on this now

**Comment by kiadso** [comment]
Turned out to not be a time-out issue, but when Eva crashes, this sequence is triggered. It was really related to Issue #154

**Comment by kiadso** [comment]
Leaving open since an app crash should not mimic a session timeout.

**Comment by alex-silverman** [comment]
here's the PR for this: https://github.com/abtassociates/eva/pull/165
