### ISSUE TITLE
Null GrantID Question

### ISSUE THREAD

**Issue by LaurenBianchi** [abtassociates/eva#172]
**Describe the bug**
I am receiving an error in relation to GrantID.
- Issue: Nulls not allowed in this column
- Type: Error
- Guidance: The GrantID column in the Funder file contains nulls where they are not allowed. This could mean the column has an incorrect data type and was not imported or it could mean 1 or more values are null where they should not be.
There are no nulls in this column or unpermitted characters per the CSV specifications. 
I saw in a [previous issue ](https://github.com/abtassociates/eva/issues/150) that the guidance was that there were to be quotes around the string but we have that implemented and are still receiving this flag on our test dataset. 

This error is not causing a rejection, but I would love to upload a file without any errors. 

Any guidance/insight would be greatly appreciated.

**Comment by alex-silverman** [comment]
Hi @LaurenBianchi,

To help diagnose this issue, could you try uploading your file to our test application here:

https://hmis-stage.abtsites.com/additional_structure_details/

This version of the application will tell you in the Structure Analysis Detail export which row(s) are affected by this issue. That may help us narrow down what's going wrong.

**Comment by LaurenBianchi** [comment]
Thanks, @alex-silverman!
Do you know if the row identified in the HMIS CSV Export File Structure Analysis excludes or includes the header row? 
I checked both just in case and they both appear to be allowable Grant ID strings: N/A or Scrooge Mcduck (test data is always fun).

**Comment by alex-silverman** [comment]
It should *exclude* the header.

In any case, we did a little testing here and discovered that R automatically treats the value NA as a null. On the other hand, the values N/A, n/a, and na are all treated as non-null. So if your file has some values that are NA, these will be flagged as nulls. Does that explain your situation?

Thank you for bringing this to our attention! In our next patch, which should be next Thursday, 2/23, we will include a fix for this to allow the value NA.

In the meantime, I have pushed this fix to the staging site, in case that's helpful. Please note, though, that the staging site will be taken down tomorrow morning.
