### ISSUE TITLE
EVA crash?

### ISSUE THREAD

**Issue by jrobinson21** [abtassociates/eva#209]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
I am unable to upload my file because I am being told EVA has crashed

**To Reproduce**
1. Click here to get started
2. Click browse
3. Upload zip file

**Expected behavior**
Zip file updates and I am able to run the tool

**Desktop (please complete the following information):**
 - Operating System: 19042.2604
 - Browser: Google Chrome

**Additional context**

**Comment by kiadso** [comment]
Hi @jrobinson21,

Thank you for putting in this issue. Can you send a screenshot of the error you are seeing? Or copy the exact words you're seeing?

Much appreciation-

**Comment by jrobinson21** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/127421733/224081727-471813fa-b1ff-4883-947d-638012227f88.png)

**Comment by alex-silverman** [comment]
Hi @jrobinson21,

Were you able to successfully upload any files? If so, did you ever see a pop-up indicating that your upload was successful?

I've created a temporary test/debugging application here: 

https://hmis-stage.abtsites.com/eva-main

Would you mind trying to re-upload the zip file that failed and let me know when you have? I will check the log and should have a better idea of what's going wrong.

**Comment by jrobinson21** [comment]
It did not successfully upload. I tried to reupload and it still says it crashed.

**Comment by alex-silverman** [comment]
Sorry, so just to clarify, you tried uploading (and re-uploading) your zip file to the test app I linked to above, right? And the crash happened at the same point as your original screenshot? 

If so, this is highly unusual, as the code is not even reaching the point of processing the upload. It seems like it's crashing before the file is fully uploaded to our app, before our app even touches the upload.

Would you be able to screenshot the contents of your zip file in an Explorer/Finder window?

**Comment by alex-silverman** [comment]
In case it's helpful, this is the sort of screenshot I think would be helpful:

![image](https://user-images.githubusercontent.com/3285721/224821773-abb1b58e-32e7-4515-a87d-e8c60d2e1734.png)

On the left side is by explorer window, which shows the valid path to the zip file and confirms the extension to be .zip. On the right is what I see when I open the zip file, and it shows the various csv files that we expect to be in there.

**Comment by kiadso** [comment]
HI @jrobinson21 
We have a recent issue entered very similar to yours where the uploaded file was not an HMIS CSV Export. Please reopen this Issue if your upload looks like the above image that Alex posted but you're still getting a crash.
Thank you!
