### ISSUE TITLE
 Eva Crashed

### ISSUE THREAD

**Issue by haleybutton** [abtassociates/eva#214]
I am having the same issue as another user with the EVA has crashed error. 
I click on get started. 

I go to browse to upload file 

I get error box saying EVA has crashed. 

I tried to upload a Zipped file and a single cvs file but both ways gave me the Eva has crashed error. 

I got this error at least 4 times on 3/17/2023 around the 3-3:15pm timeframe.

**Comment by kiadso** [comment]
Hi Haley,
Can you upload a screenshot of the contents of your zip file? Something like this:

![image](https://user-images.githubusercontent.com/7561522/226037743-63d518ab-3009-4503-adfa-3d4e7a6c18c7.png)

On the left side is by explorer window, which shows the valid path to the zip file and confirms the extension to be .zip. On the right is what I see when I open the zip file, and it shows the various csv files that we expect to be in there.

**Comment by haleybutton** [comment]
![image](https://user-images.githubusercontent.com/128186853/226045255-cd0a9857-d944-4062-bc10-dce740bb18ca.png)

**Comment by haleybutton** [comment]
Sorry, didn't mean to close issue. This is the path and the zipped files I was trying to upload as well as dragging a few of these individually.

**Comment by kiadso** [comment]
Ok, it looks like you are uploading an APR and not an HMIS CSV Export. Please contact your vendor for instructions on how to get a hashed zipped HMIS CSV Export from your HMIS. 

We appreciate this screenshot- we will add more nuance to the upload process so that instead of crashing, Eva will tell you what you are missing!
