### ISSUE TITLE
Vendor unresponsive in fixing errors-req alt assistance 

### ISSUE THREAD

**Issue by dblakegkcceh** [abtassociates/eva#240]
Our vendor is struggling to resolve our high priority file structure analysis. I am trying to find alternative ways to resolve the following errors and would appreciate guidance. 

I have attached the file structure analysis that was produced. 
[File-Structure-Analysis-2023-04-04.xlsx](https://github.com/abtassociates/eva/files/11152424/File-Structure-Analysis-2023-04-04.xlsx)

**Comment by alex-silverman** [comment]
Hello. Apologies for the delay. We are discussing this with our team to get you an answer as soon as possible.
