### ISSUE TITLE
"Eva has crashed" error upon trying to drop 7-zip file into Eva portal

### ISSUE THREAD

**Issue by MDHTRH** [abtassociates/eva#275]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
Per HUD AAQ case #213769 I am reporting this item on github since HUD told me to report on this platform today.....read on.
FYI, we do get a zip file.....it's just that this new format is 7-zip format.

=========================================================================

I have been advised by our vendor, Wellsky, to contact you on this Eva item.

We are running the new Eva export via a "hashed HMIS csv" report tab that was installed during a system upgrade last week Friday night. 

This new downloadable format is type 7zip.  I and another System Admin at our site have both individually tried a download and also tried to drop the new 7zip file into Eva but Eva has crashed every time we drop the files into the Eva folder.  I am able to manually click on the 7zip file and each individual folder opens up and all is readable.  That part is ok.  It's the Eva part that is "crashing" that is supposed to show the HIGH PRIORITY, ERROR, etc., etc., tabs and all.  Please see attached doc with screen prints in AAQ case 213769.

Previously we were getting zipped files and Eva was able to accept and process those zipped files but for some reason it it not reading these 7zip files.

Are we missing something ?

**Comment by alex-silverman** [comment]
Hello - Sorry for the trouble you're having! Unfortunately, Eva can only import .zip files, not .7zip. We have updated the app to better reflect this situation, but if you need help converting to a .zip format, please contact your vendor.

**Comment by MDHTRH** [comment]
hi alex:

Sorry, I didn't know i was supposed to answer back !

Yes, please close for me.

I contacted our vendor and they have resolved the "zip" vs "7-zip" issue that we were having.

Thx.
________________________________

**Comment by alex-silverman** [comment]
No problem at all! Thanks for following up!
