### ISSUE TITLE
Nulls not allowed or incorrect data type

### ISSUE THREAD

**Issue by RWHumboldt** [abtassociates/eva#283]
I've tried to upload zip files for a street outreach project and a shelter and I'm getting the following errors:

The PrioritizationStatus column in the Assessment file contains nulls or incorrect data types. For example, see row 1
The AssessmentType column in the Assessment file contains nulls or incorrect data types. See rows: 124

These are not SSO-CE projects. All of the street outreach and shelter clients listed in the assessment file had a Coordinated Entry assessment recorded in the Coordinated Entry project, and in many cases prioritization status was left blank. This is often left blank after intake until the prioritization status has been determined. I am not understanding why this would cause an issue with getting an EVA report on a street outreach or shelter project or what to do about it. Please advise. The vendor has told us there is nothing wrong with the file structure and that we should ask HUD.

**Comment by alex-silverman** [comment]
Hello,

Thank you for your question, and sorry for the issues you're having! While these columns should not be null according to the [HMIS CSV Specifications](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf) (see page 31), we will adjust Eva by the end of the week to allow you to proceed, despite the nulls. We will also reach out to HUD to request a review of the requirement that this field cannot be null.

I will close this comment, but please submit a new one if anything else comes up.

Alex

**Comment by RWHumboldt** [comment]
I just tried to use Eva and I'm still having the same problem. Do I have to do another Github thing?

Issue
Type
Guidance
Nulls not allowed or incorrect data type
Error
Either there is a column with nulls where they are not allowed, or there is a column with an incorrect data type. Please review the HMIS CSV Format Specifications for the data types and null requirements associated with the file and column listed in the detail and make the necessary updates.
Nulls not allowed or incorrect data type
Error
Either there is a column with nulls where they are not allowed, or there is a column with an incorrect data type. Please review the HMIS CSV Format Specifications for the data types and null requirements associated with the file and column listed in the detail and make the necessary updates.


Robert Ward, JD
Housing and Assistance Coordinator
Humboldt County Dept. of Health and Human Services
507 F Street
Eureka, CA 95501
(707) 298-3499
