### ISSUE TITLE
Download System-wide Client Counts Button Not Working

### ISSUE THREAD

**Issue by trevinflick** [abtassociates/eva#285]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
System-wide counts button will open a new browser tab not show any report

**To Reproduce**
1. Go to Client Counts tab
2. Click on Download System-wide button
3. Open new browser tab
4. See blank browser tab

**Expected behavior**
Expect csv or Excel file in browser

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Browser: (in Chrome it shows an html file in the downloaded section but says "Failed - Server problem"

**Comment by kiadso** [comment]
Hi Trevin,

Are you using a VPN? We can't reproduce this, so we're not sure what's going on. Also, can you give us the date and time it happened so we can find your activity in the logs?

Thanks!

**Comment by kiadso** [comment]
Also can you clear your cache and try again?

**Comment by trevinflick** [comment]
I'm not using a VPN. Not sure of initial time but cleared cached and tried again on both Firefox and Chrome with the same issues (1:08 and 1:09pm ET)

**Comment by alex-silverman** [comment]
This was really helpful information and we think it's helped us identify the problem. We are working on a fix and will let you know here as soon as it's updated.

**Comment by kiadso** [comment]
Hi @trevinflick, 

We think this is resolved on Eva now. If you still have problems with this, please reopen this Issue.

Thanks for your testing and help with identifying the issue.

Genelle :)
