### ISSUE TITLE
Conflicting Health Insurance and Conflicting Non-Cash Benefits Issues

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/eva#306]
Hello,

The generated HASHED CSV Export indicates in the IncomeBenefits.csv file:

- InsuranceFromAnySource=0 (no), all Insurance columns are exported as 99 (unknown)
- BenefitsFromAnySource=0 (no), all Benefits columns are exported as 99 (unknown)

When uploaded, these generate the errors:

- Conflicting Health Insurance yes/no at Entry/Exit
- Conflicting Non-cash Benefits yes/no at Entry/Exit

There are "No" Insurance or Benefits indicated and they are all set to unknown; we are also stating 0=No for InsuranceFromAnySource and BenefitsFromAnySource.  How best can this be resolved so that the EVA DQ Tool does not generate errors?

Thanks

**Comment by TanyaPieterse** [comment]
Hi Genelle,
I could not find any guidance in the CSV Specifications, and the Data Standard dependency fields only indicate the following:

- If YES (1) for Income from any source - indicate the dependent fields/sources
- If YES (1) for Non-Cash Benefits - indicate the dependent fields/sources
- If YES (1) for Health Insurance - indicate the dependent fields/sources

What is happening in the CSV export is that the above 3 main questions are being exported correctly as a NO (0).  BUT then the dependent questions are exported as a 99 if they are not entered.  This seems to be causing the error in the EVA DQ Tool indicating conflicting information.

Should the EVA DQ Tool not only look at where the 3 main questions are indicating a "Yes" to see if anything was entered in to the dependent fields?

Thanks,

**Comment by kiadso** [comment]
Hi Tanya,

In the HMIS Data Standards Manual FY2022 (and FY2024) it says on page 113 (notice in particular the last bullet):

**System Logic and Other System Issues:** The system must record the appropriate data collection stage for each record of this data element. Systems must allow users to create 'update' records to document changes between required collection points. Allow corrections for data entry errors at all stages. Data for the fields of this element should be logically consistent. It is recommended that the HMIS is programmed to enforce these rules or to notify users when inconsistent data has been entered.

• If there is a "yes" response to 'Income from Any Source' then at least one source of income must be identified.
• If a source is identified, then a 'Monthly Amount' must be entered.
• If a 'Monthly amount' is entered for any source, then a 'Total monthly income' amount is required
• If there is a "no" response to 'Income from Any Source' then the HMIS must automatically record all sources as "no" and leave dollar amounts null of $0.00.

This ^ is where this logic in Eva is coming from. I'm going to close this Issue, but if you have further questions or concerns, please respond here.

Thank you

**Comment by TanyaPieterse** [comment]
Hi Genelle,

Thank you for the guidance!  That last bullet point was helpful, I incorporated more error handling into our screens to ensure when they select a “No” that all the sources will also indicate a “No” instead of “Unknown”.

We will clean up the client data and ask them to upload their file to EVA again.

Thanks,

Tanya Pieterse
Bell Data Systems, Inc.<https://belldatasystems.com/>

[BellData New Logo Email]

  *   ***@***.******@***.***>

  *   (888) 845-0460 x202

  *   (877) 845-0460

IMPORTANT: To protect client privacy, please refer to clients using their Card ID number only (found on the Demographics Screen). Do not send screenshots that include sensitive client information, such as name, DOB, SSN, etc.

Confidentiality Notice: This email transmission, and any documents, files or previous email messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by replying to the email and destroy the original transmission and its attachments without reading or saving them to disk.
