### ISSUE TITLE
Eva Crashing

### ISSUE THREAD

**Issue by TanyaPieterse** [abtassociates/eva#311]
Hello,
![image](https://github.com/abtassociates/eva/assets/44713006/9895566e-f652-4811-8db1-ce9e73e7e545)

The file upload kept crashing around 3:33pm EST on 07/12/2023.  Is it possible to see what made the upload crash EVA? I am using Google Chrome to upload.

Thanks,

**Comment by kiadso** [comment]
Hi Tanya,

Thank you so much for reporting this. Eva seems to be down. We are looking into this now.

I'll keep you updated!

Genelle

**Comment by kiadso** [comment]
Hi @TanyaPieterse 

Eva should be back up now.

We are going to take Eva offline tomorrow between 9a and 11a ET for maintenance, just as an fyi.

Thanks again, we really appreciate the report.

Genelle

**Comment by TanyaPieterse** [comment]
Hi Genelle,

Thanks!  It is working perfectly now.

Tanya Pieterse
Bell Data Systems, Inc.<https://belldatasystems.com/>

[BellData New Logo Email]

  *   ***@***.******@***.***>

  *   (888) 845-0460 x202

  *   (877) 845-0460

IMPORTANT: To protect client privacy, please refer to clients using their Card ID number only (found on the Demographics Screen). Do not send screenshots that include sensitive client information, such as name, DOB, SSN, etc.

Confidentiality Notice: This email transmission, and any documents, files or previous email messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution, or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by replying to the email and destroy the original transmission and its attachments without reading or saving them to disk.
