### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by VickieBAHS** [abtassociates/eva#313]
When downloading from HMIS to my computer the encrypted file says "Failed - Virus Detected" 

**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kiadso** [comment]
Hi @VickieBAHS 

If you downloaded something from your HMIS system and your computer thinks it contains a virus, please contact your vendor and/or your internal IT department.

Thank you-
Eva team
