### ISSUE TITLE
Nulls not allowed or incorrect data type

### ISSUE THREAD

**Issue by RWHumboldt** [abtassociates/eva#315]
I'm still getting an error when trying to use Eva:

Nulls not allowed or incorrect data type | Error | Either there is a column with nulls where they are not allowed, or there   is a column with an incorrect data type. Please review the HMIS CSV Format   Specifications for the data types and null requirements associated with the   file and column listed in the detail and make the necessary updates.

Detail
--
The AssessmentType column in the   Assessment file contains nulls or incorrect data types. See rows: 124
The PrioritizationStatus column in the   Assessment file contains nulls or incorrect data types. For example, see row   6

**Comment by alex-silverman** [comment]
Hi Robert - you should be able to proceed despite the errors. Is that not the case? The reason these are still errors is that these fields shouldn't be null according to the [HMIS CSV Specifications](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf) (see page 31). We merely changed the issue type to be "Error" instead of "High Priority", so that you could proceed. 

We still plan to reach out to HUD to request a review of the requirement that this field cannot be null.

**Comment by RWHumboldt** [comment]
Some of the issues still say "error"

***@***.***

**Comment by alex-silverman** [comment]
Hi Robert - I'm a little confused by your question. Eva's main job is to identify and flag data quality issues in your HMIS csv file. For example, if there are nulls in a field that shouldn't have nulls, like PrioritizationStatus, then Eva **should** **and will** flag it as an "error". If there are no "High Priority" issues, then you should still be able to proceed with the tool in order to view other data quality issues.

**Comment by RWHumboldt** [comment]
As I explained in the original thread about this, prioritization status is often left blank because the people doing the initial intake can’t determine the prioritization status, and my understanding was that you were going to adjust Eva so that I could proceed while we wait for HUD to look at the issue.

Robert Ward, JD
Housing and Assistance Coordinator
Humboldt County DHHS
507 F Street
Eureka, CA 95501
(707) 298-3499
________________________________

**Comment by RWHumboldt** [comment]
I am unable to proceed- in the screenshot I included you can see that one line says high priority and the other says error

Robert Ward, JD
Housing and Assistance Coordinator
Humboldt County DHHS
507 F Street
Eureka, CA 95501
(707) 298-3499
________________________________

**Comment by alex-silverman** [comment]
Ah. I did/do not see a screenshot. Would you mind trying to attach it again so I can see which columns it is saying are null and High Priority? You may need to download the File Structure Analysis file to view this level of detail.

**Comment by RWHumboldt** [comment]
I've attached the file structure analysis. I uploaded a hashed CSV export of a supportive services only project (drop in center, not a CE project). The assessment level error example that's listed in the analysis involves a client of the SSO project who enrolled in the CES project, and someone recorded that they were placed on the prioritization list without recording the assessment level. Obviously an error, but isn't that what Eva is for- finding the errors? I don't know why that would stop us from using Eva entirely. Is the issue that our vendor is required to program the system so that it's impossible for a user to do that? Also I don't know why an error in the CES intake would prevent me from using Eva on an SSO (not CE) project.

The other high priority issue is:

The CurrentLivingSituation column in the CurrentLivingSituation file contains nulls or incorrect data types. See rows: 1369

In this case there is just one client in the whole file where a contact was recorded, but current living situation was left blank- another obvious error. Is the issue that the vendor is supposed to set up the system such that it is impossible to create a contact while leaving the current living situation blank?

Robert Ward, JD
Housing and Assistance Coordinator
Humboldt County Dept. of Health and Human Services
507 F Street
Eureka, CA 95501
(707) 298-3499

**Comment by RWHumboldt** [comment]
Just tried another upload and still getting these errors:

Issue
Type
Guidance
Detail
Nulls not allowed or incorrect data type
Error
Either there is a column with nulls where they are not allowed, or there is a column with an incorrect data type. Please review the HMIS CSV Format Specifications for the data types and null requirements associated with the file and column listed in the detail and make the necessary updates.
The AssessmentType column in the Assessment file contains nulls or incorrect data types. See rows: 6, 7
Nulls not allowed or incorrect data type
Error
Either there is a column with nulls where they are not allowed, or there is a column with an incorrect data type. Please review the HMIS CSV Format Specifications for the data types and null requirements associated with the file and column listed in the detail and make the necessary updates.
The PrioritizationStatus column in the Assessment file contains nulls or incorrect data types. For example, see row 1


From: Ward, Robert
Sent: Wednesday, July 19, 2023 8:34 AM
To: abtassociates/eva ***@***.***>; abtassociates/eva ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [abtassociates/eva] Nulls not allowed or incorrect data type (Issue #315)

I've attached the file structure analysis. I uploaded a hashed CSV export of a supportive services only project (drop in center, not a CE project). The assessment level error example that's listed in the analysis involves a client of the SSO project who enrolled in the CES project, and someone recorded that they were placed on the prioritization list without recording the assessment level. Obviously an error, but isn't that what Eva is for- finding the errors? I don't know why that would stop us from using Eva entirely. Is the issue that our vendor is required to program the system so that it's impossible for a user to do that? Also I don't know why an error in the CES intake would prevent me from using Eva on an SSO (not CE) project.

The other high priority issue is:

The CurrentLivingSituation column in the CurrentLivingSituation file contains nulls or incorrect data types. See rows: 1369

In this case there is just one client in the whole file where a contact was recorded, but current living situation was left blank- another obvious error. Is the issue that the vendor is supposed to set up the system such that it is impossible to create a contact while leaving the current living situation blank?

Robert Ward, JD
Housing and Assistance Coordinator
Humboldt County Dept. of Health and Human Services
507 F Street
Eureka, CA 95501
(707) 298-3499

**Comment by alex-silverman** [comment]
Hi Robert - Based on your email it looks like Eva is still flagging Nulls for **AssessmentType** and **PrioritizationStatus** as "Errors", rather than"High Priority". Is that right? If so, this is in accordance with the HUD Data Standards, which say that these fields should not be null. The key is that they are labelled as "Errors" rather than "High Priority", as issues of the latter type prevent using the rest of the tool.  We are still working on demoting Nulls for **AssessmentLocation** and **CurrentLivingSituation** to "Errors". However, please note that all of these fields SHOULD NOT be null, so Eva is working as intended by flagging them as "Errors".

Feel free to give me a call if this is still unclear.

**Comment by RWHumboldt** [comment]
You're right, it's working. Thank you!

**Comment by RWHumboldt** [comment]
I just did an export on a different project- street outreach this time- and I'm still getting a high priority issue that is preventing me from moving forward:

Nulls not allowed or incorrect data type
The CurrentLivingSituation column in the CurrentLivingSituation file contains nulls or incorrect data types. For example, see row 2

Could you switch this so it generates an error rather than being "high priority"? We would like to use Eva to identify errors like this- ideally it would not prevent us from running the DQ report.

**Comment by alex-silverman** [comment]
Hi Robert - We are still working on demoting Nulls for AssessmentLevel and CurrentLivingSituation to "Errors". We will update this issue as soon as we've made the update.

**Comment by RWHumboldt** [comment]
Thanks!
