### ISSUE TITLE
"You have uploaded an unhashed version of the HMIS CSV Export"

### ISSUE THREAD

**Issue by RWHumboldt** [abtassociates/eva#316]
I'm trying to upload a hashed HMIS CSV export for our CES project using the "Hashed HMIS CSV" export feature in ServicePoint (WellSky) and Eva is telling me:

"You uploaded an unhashed data set
You have uploaded an unhashed version of the HMIS CSV Export. If you are not sure how to run the hashed HMIS CSV Export in your HMIS, please contact your HMIS vendor."

I was able to upload a hashed HMIS CSV export for a different project successfully just this morning, so I don't believe the files I'm trying to upload are unhashed.

**Comment by kiadso** [comment]
Hi RW,

A way to tell if it was exported as hashed it to open the Export.csv file and check that the "HashStatus" is 4. If it isn't, then your HMIS did not hash the export.

I would recommend trying again. If you are still unable to get a hashed file, please contact your vendor.

If HashStatus is actually 4 and Eva is saying it is not hashed, then respond back here.

Thanks
