### ISSUE TITLE
Eva thinks my HMIS CSV Export is not structurally valid, but it is.

### ISSUE THREAD

**Issue by RWHumboldt** [abtassociates/eva#317]
I am uploading a hashed CSV export for a RRH project and Eva is telling me:

Unsuccessful Upload: Your HMIS CSV Export is not structurally valid
Your HMIS CSV Export has some High Priority issues that must be addressed by your HMIS Vendor. Please download the File Structure Analysis for details.

The file structure analysis includes the following high priority issues that are preventing me from accessing the DQ report:

The AssessmentLevel column in the Assessment file contains nulls or incorrect data types. See rows: 1

So I checked the AssessmentLevel column in the Assessment file and found three assessments all of which had the value "2" which indicates that we did a housing needs assessment. That is not an incorrect data type- I've been successfully uploading hashed CSV files to Eva that have that value in that column.

A possible solution would be to change this from a high priority issue to an error.

 - Operating System: Windows 11
 - Browser: Edge

**Comment by kiadso** [comment]
Hi RW,

Can you please call me before 3pm ET? Or we can work out a time to do a screenshare tomorrow if that's not a good time.

Thanks!
Genelle
301.347.5705
@RWHumboldt

**Comment by RWHumboldt** [comment]
User error- thanks Genelle
