### ISSUE TITLE
Export File Structure Error

### ISSUE THREAD

**Issue by scampillo** [abtassociates/eva#338]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
Type: Error Nulls not allowed or incorrect data type

**To Reproduce**
Upload HMIS CSV export
1. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**
[File-Structure-Analysis-2023-08-17.xlsx](https://github.com/abtassociates/eva/files/12372695/File-Structure-Analysis-2023-08-17.xlsx)

**Comment by kiadso** [comment]
Hi @scampillo 

Do you have a question? I'm not seeing it, just the suggested issue template and your file structure analysis file.

Thanks!

**Comment by kiadso** [comment]
Hi, 

It looks like you uploaded your file to Eva successfully, which means you can use Eva without any problems. 

There are no High Priority issues listed in the file you uploaded, so there isn't anything to be done on our end. The errors in your File Structure Analysis mean that your vendor either didn't populate or didn't format the columns named (Enrollment.DateUpdated, EnrollmentCoC.DateUpdated, EmploymentEducation.DateUpdated, HeathAndDV.DateUpdated, and IncomeBeneifits.DateUpdated) according to the [HMIS CSV Specifications](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf), but even with those issues, your file was successfully uploaded and you can still use Eva. If your vendor wants to know whether their HMIS CSV Export is in compliance with the HMIS CSV Export specifications, this file can help them with that. 
Thanks,
Genelle

**Comment by scampillo** [comment]
Perfect!  Thank you. When I reached out to our vender; they suggested I submit a ticket with you.
