### ISSUE TITLE
Eva has crashed

### ISSUE THREAD

**Issue by pocketfishy** [abtassociates/eva#339]
**Describe the bug**
Eva crashes when uploading a test file with the 2024 HMIS data standards

**To Reproduce**
1. Go to https://hmis.abtsites.com/eva/
2. Upload .zip file using 2024 data standards
3. See error

**Expected behavior**
To see data quality results, error messages, etc...

**Screenshots**
![image](https://github.com/abtassociates/eva/assets/110262695/40ec519c-64af-477a-996a-7fdb4e4a8068)

**Desktop (please complete the following information):**
 - Operating System: Windows 10 Pro - OS Build 19045.3324
 - Browser: Chrome - Version 116.0.5845.96 (Official Build) (64-bit)

**Other Info**
Error occurred at 8:37am PT August 21, 2023

**Comment by pocketfishy** [comment]
Hi @kiadso, thanks for getting back with me quickly. My understanding is that the 2024 data standards will take effect on October 1st, 2023. That's just over a month away. Does the team that developed eva plan to update the software to accommodate the new file format? If so, do you have a sense of when that will be?

![image](https://github.com/abtassociates/eva/assets/110262695/0db1f0b9-d9e4-461c-876b-60a32d5d999c)

https://www.hudexchange.info/news/fy-2024-hmis-data-standards-released/

**Comment by kiadso** [comment]
Hi @pocketfishy, yes Eva will be updated to accept FY2024 files then.

**Comment by pocketfishy** [comment]
@kiadso Ok, thank you!
