### ISSUE TITLE
Warning "Inventory records may begin prior to a Project Operating Start Date.." 

### ISSUE THREAD

**Issue by Nancye28** [abtassociates/eva#347]
It appears the error "Inventory records may begin prior to a Project Operating Start Date" does not take into account that multiple inventory records exist within the provider. 

This is an error that appeared for an already established program (SSVF RRH) where the inventories change from year to year. This error appeared because EVA is looking at the most recent "open" inventory record and not former or inactive inventory records. 

This is an error within the report.

**Comment by kiadso** [comment]
Hi @Nancye28,

For the inventory record that is being flagged, what is that record's Inventory End Date?

Thanks for the clarification-

Eva dev team

**Comment by kiadso** [comment]
Ok, so the problem is it is checking inactive inventory records, I see. Thanks for reporting!

**Comment by Nancye28** [comment]
Hello, I see this ticket is closed, but it is still coming up in error. The system is disregarding multiple inventory records.

It appears the FY24 version is not correct. The errors read as follows:

Warning | Inventory Start Precedes Operating Start | Inventory records may begin prior to a Project Operating Start Date, but sometimes this can indicate an incorrect date in either the Project Operating Start or the Inventory Start Date. Please review and if any dates are incorrect, update the record.

**Comment by alex-silverman** [comment]
Hi @Nancye28 - the change we had made here was to ignore _inactive_ inventory records, i.e. those whose inventory dates are NOT within the Export Start and End dates (from your Export.csv file). Any _active_ inventory records whose Inventory Start Date preceded the Project Operating Start date get flagged, though only as a **warning**. It is **not necessarily a problem**. Indeed, if you export the PDDE Report and look at the Details column for this issue, you should see the following text:

"This project may have been merged with another project which would explain why the Inventory Start Date of [InventoryStartDate] is prior to the project's Operating Start Date of [OperatingStartDate]. Please be sure this is the case and that it is not a typo."

Does this help clarify things?

If not, can you clarify what you mean by "the system is disregarding multiple inventory records" and send a screenshot within GitHub (not via email) of your Inventory.csv file, specifically showing those particular records? That will help us better understand your issue.

**Comment by Nancye28** [comment]
All of our errors have been cleared. 

Thank you!
