### ISSUE TITLE
Inquiry about warning

### ISSUE THREAD

**Issue by cyounggit** [abtassociates/eva#350]
I am getting a warning on the responses to homeless history interviews that don't appear to have an issue from my perspective.  Is it possible to get clarification on why EVA has concerns about these responses:

Client A: Warning "Invalid Homelessness Start Date/Number of Months Homeless"
Client interview date: 7/12/22
Homelessness Start date: 6/6/22
Prior Living Situation: Emergency shelter
Length of stay in previous place: Two to six nights
Apprx date homelessness started: 6/6/22
# of times on the the streets, etc. in last 3 years: One time
# of months homeless on the streets in past 3 years: One month

Client B: Warning  "Invalid Homelessness Start Date/Number of Months Homeless"
Client interview date: 9/19/22
Homelessness Start date: 2/15/22
Prior Living Situation: Place not meant for habitation
Length of stay in previous place: 90 days or more, but less than one year
Apprx date homelessness started: 2/15/22
# of times on the the streets, etc. in last 3 years: One time
# of months homeless on the streets in past 3 years: 7

**Comment by kiadso** [comment]
Hi, the Guidance for that warning is:

> According to this client's assessment at Project Start, they experienced a single episode of homelessness in the three years prior to their enrollment and the approximate date homelessness started known, but the total number of months they experienced homelessness prior to this enrollment is inconsistent with the given dates. Please double-check this information for consistency and accuracy.

In the HMIS Data Standards Manual, see page 109 where it says:

> Count the cumulative number of months in which a person was on the streets, in an ES, or SH in the last 3 years, including stays in an institution less than 90 days or in permanent or transitional housing less than 7 days. **Round the number of months up to the next highest number of full months. The current month, even if a partial month, can be counted as a full month.**

So in your first example, you would count June and July (2 months) and in your second example, you would count February, March, April, May, June, July, August, and September (8 months.)
