### ISSUE TITLE
Exited clients getting "Invalid Move In Date"  

### ISSUE THREAD

**Issue by MDHTRH** [abtassociates/eva#356]
*We have a family of 3 that entered a RRH pgm on 12/16/22.  On 12/27/22 the 2 that are not HoH exited back to the street, leaving the HoH who goes on to move into housing by himself on 1/01/23.

My user just ran an Eva rpt and the 2 clients that exited on 12/27/22 back to the street are getting "**Invalid Move In Date**" errors.

I don't think this is an error even though Eva is reporting it as an error.

Is this an issue that can be looked into ASAP ?

**Comment by alex-silverman** [comment]
Hello - I am looking into this now.

**Comment by MDHTRH** [comment]
Hi Alex:

Yes, we are aware of the HMID requirements.   Remember, these 2 clients had no HMID - only the HoH had a HMID and he's the one that stayed in the pgm while the other 2 exited back to the street.

Here's the screen print of what was in the report:

[cid:6b73f596-7737-4305-ad60-8c0d5021cf56]


Here's a view of the household in the pgm Entry:

[cid:493cc42f-b2b4-4156-abd8-bf95e82e41b2]







________________________________

**Comment by alex-silverman** [comment]
If there is no HMID, then those 2 clients should not have been flagged for
this issue. Unfortunately, I can't see either of the screenshots you sent.
Any way you can reply via email, where you may have more luck attaching
screenshots?

**Comment by MDHTRH** [comment]
Hi Alex:

I just attached a WORD doc with the 2 screen prints that I cut and pasted in it.

Hope you can see the details in that doc now.....
________________________________

**Comment by alex-silverman** [comment]
I'm not sure why it won't let me see any of these. Perhaps because you're replying via email instead of in GitHub? Can you resend it to Alex_Silverman@abtassoc.com?

**Comment by MDHTRH** [comment]
[Alex 083123.docx](https://github.com/abtassociates/eva/files/12489830/Alex.083123.docx)

**Comment by MDHTRH** [comment]
OK, I went on github and dragged and dropped the WORD doc......can you see it now ?

**Comment by alex-silverman** [comment]
Yes, thank you. I see the word document. Unfortunately, I'm still puzzled, so I may need to pull in one of my colleagues for help. Without seeing the MoveInDate/HMID and EntryDate fields in the Enrollment.csv file for these folks, it's hard to say what exactly is going wrong. Eva shouldn't flag a record for "Invalid Move-In Date" that has no MoveInDate/HMID, so I'm wondering if Eva is maybe misreading a blank as a non-blank or something. Is there any way you can screenshot those fields in the Enrollment.csv file directly?

I see that you closed the issue. Does that mean you resolved it on your own?

**Comment by MDHTRH** [comment]
No, i did not close the case.  must have been a mistake.  plz reopen for me.

let me get the other screen prints you are requesting from the enrollments csv.
________________________________

**Comment by MDHTRH** [comment]
[UPDATED Alex 083123.docx](https://github.com/abtassociates/eva/files/12490093/UPDATED.Alex.083123.docx)

Hi Alex:
I updated the WOR doc and added 2 more screen prints for you.   The enrollments are there and it looks like Eva added the HMID of 1/1/23 in for both clients that left the pgm early.  Notice the Entry for client 288170 where Move In Date is blank !
 Thx.

**Comment by MDHTRH** [comment]
ok Alex.....see the github case.  I updated and added additional screen print with enrollments and Entry screen print as well.

Thx.
________________________________

**Comment by alex-silverman** [comment]
Thank you for sending the updated doc. I think that explains it. The
MoveInDate in your screenshot is 1/1/2023, which is after the 12/27/2022
ExitDate, so that is what's tripping Eva's data quality check.

I know you said you didn't think these two people had move-in dates. Do you
have any idea why they may be in your Enrollment.csv file, and why they are
on 1/1/2023 if the clients Exited on 12/27/22?

**Comment by MDHTRH** [comment]
GM.

So I have also been reviewing this case with our vendor, Wellsky.

They have determined that our HMIS is assigning move in dates to household members via the HoH's move in date even if the household members have exited before HoH gets a move in date.  This case has been added to their list of outstanding issues to be addressed.

Please close this github case re: housing move in date because it is not an Eva issue after all.

Thanks.

________________________________
