### ISSUE TITLE
Missing Geography Information

### ISSUE THREAD

**Issue by onazarian** [abtassociates/eva#364]
The PDDE Eva report indicates that some projects are missing geography information. The addresses for these projects are also missing. I checked the system for the project addresses and found no errors. I also contacted the vendor, but they were unable to find any errors.

**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kiadso** [comment]
Hi, if you check the projectcoc.csv file for missing data, you should see
where the missing data is. Contact your vendor if what you're seeing in
your export doesn't match what you're seeing in your HMIS.

Thanks!

**Comment by onazarian** [comment]
Hi,

Thank you for your response.

I am getting errors for the following projects: [Adult Center, USHS FSC Crisis Housing Family Center, Elizabeth House TH, B7 Bridge Housing Program Adult Center and HEAP PAS Weather activated Motel Vouchers PPHD].

Could you please let me know which column I should look for errors in?

ProjectID
OrganizationID
ProjectName
ProjectCommonName
OperatingStartDate
OperatingEndDate
ContinuumProject
ProjectType
HousingType
ResidentialAffiliation
TrackingMethod
HMISParticipatingProject
TargetPopulation
HOPWAMedAssistedLivingFac
PITCount
DateCreated
DateUpdated
UserID
DateDeleted
ExportID
1250
69
Adult Center
4/11/2013
1
1
1
0
1
4
2
4/11/2013 8:25
3/21/2022 13:22
21
236127
1450
69
USHS FSC Crisis Housing Family Center
3/5/2015
1
1
1
3
1
4
2
3/4/2015 11:38
2/8/2023 16:04
18
236127
1953
172
Elizabeth House TH
5/13/2009
1
2
1
1
4
2
12/4/2008 15:02
12/5/2022 9:58
27
236127
2571
69
B7 Bridge Housing Program Adult Center
10/1/2017
1
1
1
3
1
4
2
10/17/2017 15:53
7/31/2022 21:30
18
236127
4498
366
HEAP PAS Weather Activated Motel Vouchers PPHD
1/5/2021
7/1/2021
1
1
3
3
1
4
2
1/14/2021 16:04
6/1/2023 10:16
27
236127


Thank You
Onik

Onik Nazarian
HMIS System Administrator
City of Pasadena
Department of Information Technology
Phone: (626) 744-8328
Fax:        (626) 396-7658
E-mail: ***@***.******@***.***>

**Comment by alex-silverman** [comment]
Hello - I think you may be looking at the Project.csv file, which is different from the ProjectCoC.csv file. Eva's PDDE export should provide some additional detail on exactly which columns (and potentially rows) contain the missing data. The "Missing Geography" error is flagged if one or more of the following fields is missing data in that ProjectCoC.csv file:

- CoCCode
- Address1
- City
- State
- Geocode
- GeographyType

**Comment by onazarian** [comment]
Good Morning,

Thank you for responding,

Yes, the following projects are missing the following information: Address1, City, State, Geocode, and GeographyType. I have listed them below, with the missing information highlighted in yellow:

These projects are CA-600 CoC, LAHA's projects, which they created under Pasadena's CA-607 site.

Would you be able to make some changes to the coding so that it does not show up CA-600 CoC Code on any of CA-607 CSV reports (Affiliation, Assessment, AssessmentQuestions, AssessmentResults, Client, CurrentLivingSituation, Disabilities, EmploymentEducation, Enrollment, EnrollmentCoC, Event, Exit, Export, Funder, HealthAndDV, IncomeBenefits, Inventory, Organization, Project, ProjectCoC, Services, Userand YouthEducationStatus) in the future?


ProjectCoCID
ProjectID
CoCCode
Geocode
Address1
Address2
City
State
ZIP
GeographyType
DateCreated
DateUpdated
UserID
DateDeleted
ExportID
22568
1250
CA-600
0






12/1/2021
3/21/2022
21
3/21/2022
236127
22479
1450
CA-600
0






9/30/2021
3/21/2022
21
3/21/2022
236127
3849
1953
CA-600
0






10/23/2017
10/24/2017
27
10/24/2017
236127
15482
2571
CA-600
0






11/20/2018
3/21/2022
21
3/21/2022
236127
22570
4498
CA-600
0






12/1/2021
12/1/2021
27

236127
20790
1250
CA-607
62724
412 S Raymond Ave
Pasadena
CA
91105
1
12/5/2019
12/5/2019
27
236127
20057
1450
CA-607
62724
825 E. Orange Grove Blvd.
SPA 3
Pasadena
CA
91104
1
7/26/2019
7/26/2019
18
236127
18827
1953
CA-607
62724
760 Santa Barbara St
Pasadena
CA
91101
1
4/16/2019
4/16/2019
27
236127
15483
2571
CA-607
62724
412 S Raymond Ave
Pasadena
CA
91105
1
11/20/2018
11/20/2018
5506
236127
21952
4498
CA-607
62724
1845 N Fair Oaks Ave
Pasadena
CA
91103
1
1/14/2021
1/14/2021
27
236127


Thank You
Onik

Onik Nazarian
HMIS System Administrator
City of Pasadena
Department of Information Technology
Phone: (626) 744-8328
Fax:        (626) 396-7658
E-mail: ***@***.******@***.***>

**Comment by kiadso** [comment]
Hi,

The data that you upload will be shown in Eva, so if you're wanting to
limit the records you want to see, please work with your vendor on how to
filter your export in the way you need it.

Thanks,

Eva dev team

**Comment by onazarian** [comment]
Thank You for responding,

Have a great day!

Thank You
Onik

Onik Nazarian
HMIS System Administrator
City of Pasadena
Department of Information Technology
Phone: (626) 744-8328
Fax:        (626) 396-7658
E-mail: ***@***.******@***.***>

**Comment by alex-silverman** [comment]
Closing this now. If you find another issue, please open a new ticket.

**Comment by onazarian** [comment]
Thank You for update,

Have great rest of day!

Thank You
Onik

Onik Nazarian
HMIS System Administrator
City of Pasadena
Department of Information Technology
Phone: (626) 744-8328
Fax:        (626) 396-7658
E-mail: ***@***.******@***.***>
