### ISSUE TITLE
Eva crashed and onscreen message said to submit an issue

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/eva#385]
I was trying to upload an export that was a few dozen programs to check the structure as we tested FY2024 data standards. (Our smaller uploads worked/passed tests but this was Foothold Technology's dor database, all the Arbor programs). Date: 9/30/2023. Time about 7:55 pm east coast time. Eva crashed.

**Comment by kiadso** [comment]
Hi Michelle,

Is the data sample data that could be shared to us for testing? If it is sample data and not real data, please email me at genelle_denzin at abtassoc dot com so we can arrange to try it in development.

If it is real data, can you send a screenshot of which files are contained in the zip file plus a screenshot of the Export.csv? I can't access the logs today, but I can at least rule out several things just by looking at how the zIp file is structured at a very basic level. 

Thanks!

**Comment by MichelleNevius** [comment]
It is not sample data. It is hashed real data. But I think while looking at the export.csv to show you the contents, I discovered the error. I'm going to discuss with a dev over here at Foothold-- but seems wrong to me that our Export.csv is producing 2 rows, one with an implementation ID value and one without, and the Implementation ID column header is missing. So I bet I found the issue. 


![zipped file contents](https://github.com/abtassociates/eva/assets/64848927/04d7fca3-bda1-4d2c-8126-3d5078e0dd4a)
![exportcsv](https://github.com/abtassociates/eva/assets/64848927/23c159f3-d1ea-4f2d-90a2-2d0a0691fea4)

**Comment by kiadso** [comment]
Hi Michelle, I agree- Eva is only expecting 1 row there and we don't have any kind of failsafe around that. We will add it so we avoid crashes going forward. Thank you for updating us! If you all correct that and are still seeing crashes, please re-open this.

**Comment by MichelleNevius** [comment]
Now that it is corrected, it no longer crashes. Thanks for your help.
