### ISSUE TITLE
eva crashed

### ISSUE THREAD

**Issue by MichelleNevius** [abtassociates/eva#394]
I was testing an import and Eva crashed and it said to report it. Here's a screenshot of files in zip file:
![image](https://github.com/abtassociates/eva/assets/64848927/8d6885b7-1e8b-452d-9081-1a06ce8ae921)

Here's a screenshot of export.csv
![image](https://github.com/abtassociates/eva/assets/64848927/49b0add6-2967-4336-a280-589c173d250a)

It's real (hashed) data from a small customer (rise) that uploads to our hmis customer in NY State, CARES.

**Comment by MichelleNevius** [comment]
yep, that worked! Thanks!

**Comment by kiadso** [comment]
Oh yeah also I'm noticing your ExportStartDate is in mdy format, but the specs say it should be ymd. Maybe Excel did that and the underlying csv has it correct

**Comment by MichelleNevius** [comment]
closing
