### ISSUE TITLE
Attempting to upload test file on prod and getting an "eva crashed"

### ISSUE THREAD

**Issue by candiceh214** [abtassociates/eva#397]
Attempting to upload test hashed file into Eva and getting an "Eva" crashed notification.  An older file with some structural issues will attempt to upload but this newer file is rejected.  12:01 PM central time on 10/11.  No other details

**Comment by kiadso** [comment]
Hi @candiceh214 ,
Could you check that your Client$MidEastNAfrican column is named correctly? We think that's why it's happening, but obviously it shouldn't be causing a crash. But on your end, fixing that should make it work. We'll work on the crashing.

Thank you!

**Comment by candiceh214** [comment]
Thank you - adjusting our file worked for us!  Sorry for the delay in response!
