### ISSUE TITLE
Zero Utilization Warnings for DV Programs in Eva's DQ reports

### ISSUE THREAD

**Issue by entomacy** [abtassociates/eva#407]
We're seeing Zero Utilization warnings in Eva's data quality for our DV shelters. They have DV target pop and comparable database HMIS participation status, so I'm wondering why we are seeing warnings about their zero participation. We would expect to see no utilization for these types of programs.

**Comment by kiadso** [comment]
Accurate! We are working on a fix for this- thank you for reporting @entomacy!

**Comment by kiadso** [comment]
Hi @entomacy,
Eva has been updated to not flag projects that are not HMIS participating for zero utilization. Also, Entry Dates should be corrected as well. THANK YOU as always for your insightful feedback and patience!
-Genelle
