### ISSUE TITLE
Overlapping CE Participation flagging without Overlap

### ISSUE THREAD

**Issue by kepaton** [abtassociates/eva#411]
**Describe the bug**
In the Check PDDE section, projects are flagging as having overlapping CE Participation records when the records do not overlap (end date 9/30/23, new start date 10/1/23) 

**Expected behavior**
When a project has more than one CE Participation record that has an end date one day before the start date of the other it should not flag as an error. 

**Screenshots**
Screenshot of the actual error language - 
![image](https://github.com/abtassociates/eva/assets/149528361/ebc4d828-e6d1-47fb-bf33-6a8ee25ea389)

**Desktop (please complete the following information):**
 - Operating System: Windows 11 Enterprise Build: 22621.2134
 - Browser: Google Chrome Version 118.0.5993.90 (Official Build) (64-bit)

**Comment by kiadso** [comment]
Hi @kepaton 

Thank you for reporting this. We will work on this and have a fix out as soon as possible.

Eva dev team

**Comment by alex-silverman** [comment]
Hi @kepaton - this should be fixed in Eva now. I will leave this issue open a bit longer in case you're still seeing the problem.
