### ISSUE TITLE
Future Exit Date Error?

### ISSUE THREAD

**Issue by mmvickers** [abtassociates/eva#418]
Hi there,

A new VA GPD project was running a DQ check in EVA today and got a Future Exit Date Error for all 26 program participants but none of the program participants have been exited from the project. The Exits CSV that we uploaded was also blank when we double checked it. 

**DO NOT UPLOAD YOUR EXPORT TO GITHUB*
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kiadso** [comment]
Hi @mmvickers 
Thank you for reporting this! Looking into it now.

**Comment by kiadso** [comment]
Hey @mmvickers when you ran your export, did you make the ExportEndDate greater than today? Like maybe you ran the export to 12/31/2023 or something like this?

**Comment by mmvickers** [comment]
Hi there, it does look like the export end date got set to 2024 by accident. Is that what is causing the issue?

**Comment by mmvickers** [comment]
Will do! Thanks so much!

**Comment by kiadso** [comment]
Hi @mmvickers,

This should be resolved now. If you still have this same problem, please reopen this issue. Thank you so much for reporting this!

-Genelle
