### ISSUE TITLE
LSA identifying Ethnicity as an error

### ISSUE THREAD

**Issue by Nancye28** [abtassociates/eva#421]
Hello, 

The download is reporting an error of "Missing Race/Ethnicity" when the client only reports as being "Hispanic/Latina/e/o" The error clears if I select a separate race like "White" in addition to ethnicity.  This seems to be a bug, is that correct? Should the system be reporting an error if a race is not selected outside of selecting Hispanic?

Thank you

**Comment by kiadso** [comment]
Hi @Nancye28,
When you say "LSA identifying..." do you mean "Eva" is identifying Ethnicity as an error? Or should this be an issue for the LSA team? Could you describe the steps you're taking to get the error? Thanks-
Thanks-
Genelle

**Comment by Nancye28** [comment]
Hello,

I uploaded the CSV to EVA, EVA is returning an error that there is a missing ethnicity for client x.  When I look up the client, in the profile, the client has the field Race/Ethnicity set to "Hispanic/Latina/e/o" but no other selection. IF I add "White" to the client's profile in addition to Hispanic (it is a multi-select field) the error no longer appears when I upload a new CSV to EVA.

Does that help clarify?

**Comment by kiadso** [comment]
Yes- we got it now- we will have a fix out for this soon!

Thank you for reporting it.

**Comment by kiadso** [comment]
Hi @Nancye28,

This should be resolved now. If you are still seeing this error, please reopen this issue. Thank you so much for reporting this!

-Genelle
