### ISSUE TITLE
Additional Race Ethnicity Column Type

### ISSUE THREAD

**Issue by mryanbender** [abtassociates/eva#434]
I got a High Priority error when uploading to Eva that the AdditionalRaceEthnicity column in the Client file is of the wrong data type. It says it should be an integer, but is a string. The CSV specs confirm that string is the correct data type. 

<img width="510" alt="image" src="https://github.com/abtassociates/eva/assets/150469334/3a661a3f-8add-4463-8bf4-47a3ab424b3a">

<img width="188" alt="image" src="https://github.com/abtassociates/eva/assets/150469334/46c9307b-cce9-4f6b-b826-263c84ff0e1c">

**Comment by alex-silverman** [comment]
Hello - we just pushed a fix for this by telling Eva to expect strings, not integers for this column. Can you please try refreshing the browser page and re-uploading your file and see if this is still showing up?

**Comment by mryanbender** [comment]
Wow, that was so fast! And it worked! I don't have that error showing now. Still have other errors, but that's with our data, not Eva. 

Thanks!
