### ISSUE TITLE
"Days since Most Recent CLS Exceeds Local Settings" Warning for Project Type 0

### ISSUE THREAD

**Issue by mryanbender** [abtassociates/eva#435]
I got 2,000+ warnings with an issue code of "Days since Most Recent CLS Exceeds Local Settings" for enrollments in Project Type 0. The Data Standards state they Current Living Situation is only required for Project Types 1, 4, 6, and 14. 

(I had warnings given by Eva for Project Types 4 and 14, but no 1 or 6 oddly enough. Not sure if that's related to this or not, but Type 0 should not be there as far as I know.)

**Comment by kiadso** [comment]
It should be checking for project types ES-NbN, Street Outreach, and Coordinated Entry but it is actually checking ES-e/e, Street Outreach, and Coordinated Entry. We will correct this as soon as possible. 

That aside, if you go to the "Edit Local Settings" tab in Eva, then expand the "Long Stayers" box, you can see that those project types are set to 90 days each. You are free to edit those 90 days to however long your CoC considers to be "too long" of a time to be enrolled in an ES-NbN, Outreach, or CE project without any kind of Current Living Situation update or Exit.

![longstayerscls](https://github.com/abtassociates/eva/assets/7561522/84478fdf-eed8-465b-bf2f-346bf8f8da67)

You can set these days higher to see fewer results. Once we have fixed the project type 1 vs 0 issue, I'll update here and let you know- thank you so much for reporting this!

**Comment by mryanbender** [comment]
Thanks, Genelle. I'll keep an eye out for the 1 vs 0 fix and then try again.

**Comment by kiadso** [comment]
Hi, this fix has been pushed to Eva today @mryanbender 

Thank you again for the report and please reopen if it's still an issue.
