### ISSUE TITLE
Income, Non-Cash, Health Insurance Errors for Project Types 14 and 1. 

### ISSUE THREAD

**Issue by mryanbender** [abtassociates/eva#436]
It looks like Eva is flagging as errors/warnings when Income, Non-Cash, and Health Insurance are missing at both entry and exit for Project Types 1 and 14. The Data Dictionary states that those elements are not required for those components. 

![image](https://github.com/abtassociates/eva/assets/150469334/091a7a69-a15b-4464-9834-3a3a9b44a99f)

**Comment by kiadso** [comment]
Noted. We will address this as soon as possible. Thank you for reporting-

**Comment by kiadso** [comment]
Hi @mryanbender,

Just to update you, we did push a rather large fix to Eva yesterday, but it didn't include a fix for this. We've started work on it, but it will likely not be pushed until November 30.

Thanks for your patience-

**Comment by mryanbender** [comment]
Thanks, I will run a new export and let you know if there are issues.
