### ISSUE TITLE
Overlapping HMIS Participation Records

### ISSUE THREAD

**Issue by scampillo** [abtassociates/eva#453]
I am seeing this error with one program:

Overlapping HMIS   Participation Records | High Priority | This project has more than one HMIS   Participation record that covers the same time period. Please be sure you are   ending any records that are no longer accurate before creating a new record.

This project's first HMIS participation period goes from 2022-05-01 to 2023-11-01, and the other participation period goes from 2022-05-01 to 2023-11-01.
This project has more than one HMIS Participation record that covers the same time period. Please be sure you are ending any records that are no longer accurate before creating a new record.

![image](https://github.com/abtassociates/eva/assets/142535880/7d8a8b55-bf0e-4d62-b93a-70e3d16223b6)

From our vendor: not familiar with the flags that occur, so it might be helpful to submit a ticket for Eva to figure out why that is being flagged since it could be a bug. I know they have had those come up recently because I'm also not seeing the two error dates on the back end.

When I view the HMIS   Participation - only 1 entry displays.  (In playing around with this setting, I did create a second record, and deleted it.)

**Comment by kiadso** [comment]
Hi @scampillo 

Just to rule out any export issues, can you go into your export zip file that you uploaded, find the HMISParticipation.csv, and search through it to be sure you don't have 2 identical records in there? 

Also, this isn't important, just curious, did this project stop operating on 11/1/2023 and that's why the participation record is ended?

Thanks!

**Comment by scampillo** [comment]
There are 3 records:
813
990
1
5/1/2022
11/1/2023
9/30/2023 20:11
11/28/2023 11:41
1381
11/28/2023 11:41
21854
1034
990
1
5/1/2022
11/1/2023
11/28/2023 11:42
11/29/2023 15:39
1381
11/29/2023 15:39
21854
1035
990
1
5/1/2022
11/1/2023
11/29/2023 15:51
11/29/2023 15:51
1381
21854

Yes, the project ended. We use clarity, and it was displaying this banner, and I was trying to see if there was a way to not have it display.
***@***.***

**Comment by kiadso** [comment]
Ah ok- it looks like the deleted records are coming through in the CSV Export. Generally we don't see that. Please let your vendor know this is happening, it may be unintentional.

**Comment by kiadso** [comment]
Thursday we will be pushing an update that will exclude deleted records upon import. If your vendor is including deleted records intentionally, your issue will be resolved EOB Thursday. If they're doing it unintentionally and they correct it before Thursday, then your issue will resolve then. :) Thank you again for reporting this @scampillo

**Comment by kiadso** [comment]
Hi @scampillo 

Eva is now ignoring deleted records so I'm going to close this, as this should resolve your issue.

Thank you!
