### ISSUE TITLE
Eva Crashed 12/18/23 3:40pm

### ISSUE THREAD

**Issue by entomacy** [abtassociates/eva#463]
Eva Crashed 12/18/23 3:40pm. Pop-up requested that I submit an issue. Last Eva attempt was this morning and we had errors in a File Structure Analysis. I was attempting to see if the vendor has resolved it the issue when it crashed.

**Comment by alex-silverman** [comment]
Hello,

Sorry for the issues you're having! Unfortunately, I'm having trouble finding your session in our logs, so I'm not able to see what might be going wrong. Would you be able to try again using this test app?

https://hmis-stage.abtsites.com/eva-dev

Once it crashes, let me know and I'll look at the test app's logs.

**Comment by alex-silverman** [comment]
Hello,

Are you still having this problem? If not, I will close the issue, as we were never able to replicate or figure out what was going wrong. Hopefully it was a fluke!

Alex

**Comment by alex-silverman** [comment]
Closing this now. Please feel free to re-open or start a new issue if you continue encountering the problem.
