### ISSUE TITLE
Issue with PATH Report Generator

### ISSUE THREAD

**Issue by kaitlit** [abtassociates/eva#468]
**Describe the bug**
First, let me apologize - I didn't take down the email for the PATH Report Generator at the HMIS lead call, but since the PATH Report Generator is loosely based in Eva, I was hoping I could reach out here.

I think there may be an issue with how it is pulling demographics. We have confirmed that our projects are running the Hashed CSV correctly from our HMIS. When we use the PATH Report Generator, for Q26 Demographics, it appears that it is pulling demographics for all clients, not just those that have an active PATH enrolled status. 

**Expected behavior**
From my reading of the PATH Annual Report specs, and how our (outdated) PATH report in HMIS runs, the sum of each demographic section of Q26 should equal the number in q15. Instead, the sum of demographic sections of Q26 appears to match the number in q8.

**Desktop (please complete the following information):**
 - Operating System: Windows 10 64-bit
 - Browser: Edge 120

**Additional context**
If there is another place to reach out to, please let me know!

**Comment by alex-silverman** [comment]
I am not familiar with the PATH report, but I will connect with my colleagues who might be, once they are back from break.

**Comment by kaitlit** [comment]
Hi - I was able to connect with Alissa about the PATH report, so the issue is resolved. Thanks and sorry for bugging you on this platform!
