### ISSUE TITLE
Enrollment Crosses Operating/Participating End Date

### ISSUE THREAD

**Issue by shsdrc** [abtassociates/eva#469]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
Hi! I saw a similar issue was open and closed describing what I've also seen, which is multiple clients being marked with the error enrollment crosses operating/participating end date. Is this a vendor issue? Am I missing something with the project set up? I'm hoping to use EVA to assist with data quality but don't want to send agency's looking for errors I can't verify/fix myself. 

There are hundreds showing this error, here is just one project example. 
All clients were enrolled 10/30/2023
![image](https://github.com/abtassociates/eva/assets/155675762/c7529f6e-1945-4448-b0e9-799c601544b9)
Screenshot from Project file showing the project is listed as operating 7/1/2023-6/30/2024
![image](https://github.com/abtassociates/eva/assets/155675762/ad7f666d-000a-4351-8a2e-e88a5456cb35)

**Desktop (please complete the following information):**
 - Browser: Google chrome 

Please let me know if any additional information is needed to look into why these errors are appearing. Thank you!

**Comment by alex-silverman** [comment]
Hello,

I hope I can clear up this confusion. Can you tell if the flagged enrollments have Exit Dates? (These can be found in the Exit.csv file of your upload.) I'm wondering if they do not or if the Exit Dates are in the future. This would cause Eva to flag these enrollments this way. For example, Eva's guidance for the `Enrollment Crosses Participating End` error says:

> This enrollment ends after the project stopped participating in HMIS. For reporting to work correctly, be sure your enrollment dates are within your HMIS participation dates.

So Eva is checking whether the enrollment's **ExitDate** is AFTER the project's **HMISParticipationStatusEndDate** from the HMISParticipation.csv file. If the ExitDate is empty or in the future, beyond the HMISParticipationStatusEndDate, then the enrollment will be flagged.

Also, please note that these are two similar but distinct errors:

1. Enrollment Crosses Operating End
2. Enrollment Crosses Participating End

The only difference is what Eva is comparing the ExitDate to. For the latter, it's comparing to the project's HMISParticipationStatusEndDate in the HMISParticipation.csv file. For the former, it's comparing to the project's OperatingEndDate in the Project.csv file.

**Comment by shsdrc** [comment]
Hello!

Can confirm all the the enrollments flagged as crosses operating and participating dates are clients who have not been exited. Therefore I see the issue is not the flag itself, but my understanding of the flag and why it is appearing. 

If this is the case, would it possibly be more appropriate to mark the issue as a warning as opposed to an error? Or to separate the particular flag into a warning for clients with ExitDate=NULL and an error for clients whose ExitDate=After Operating or Participating date? As the issue is possible, but not applicable if a client is still actively enrolled. It feels comparable to other warnings such as Possible Missed Move In-Date, which we expect to see immediately logically, but in reality does not operating in this fashion. 

RE: "So Eva is checking whether the enrollment's ExitDate is AFTER the project's HMISParticipationStatusEndDate from the HMISParticipation.csv file. If the ExitDate is empty or in the future, beyond the HMISParticipationStatusEndDate, then the enrollment will be flagged." 
To clarify, even though they are two distinct flags, does Enrollment Crosses Operating End Date flag apply in the same way but with Operating End Date?

Appreciate your response!

**Comment by alex-silverman** [comment]
Hello,

I realize now I totally missed something obvious: your project operating dates are in the future! So you're **absolutely** right that Eva should not be flagging these enrollments, because the ExitDates aren't in the future, relative to the reporting period. We will work on updating Eva accordingly. 

Thank you for bringing this to our attention! I will respond here once the change is made.

Alex

**Comment by alex-silverman** [comment]
Closing this, as the issue has been fixed in Eva! If you're still experiencing this issue, please feel free to re-open or start a new issue.
