### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by rgibson111** [abtassociates/eva#470]
I've tried several times to access the site and it says: This site can’t be reached

I even tried different networks and still doesn't work.

I've attached
![Screenshot 2024-01-10 114129](https://github.com/abtassociates/eva/assets/76067940/0934b146-1b94-4bb4-afb6-3ee4af353969)
 screenshot.

**Comment by kiadso** [comment]
Thank you so much for reporting this. We are looking into it.

**Comment by rgibson111** [comment]
As of 12:45pm EST I was able to access EVA!

Thank you!

**Comment by kiadso** [comment]
Yes, we noticed it came back online too. We are thinking it may be the servers outside of Abt that caused this, but we're looking at it more closely in case there was something we could have prevented. Thanks for your report and for your patience!
