### ISSUE TITLE
Error: No Inventory Records for Service only RRH programs

### ISSUE THREAD

**Issue by scampillo** [abtassociates/eva#471]
I am seeing error **Residential projects should have inventory data. Please enter inventory in HMIS for the project.** on the PDDE report.

The program is a RRH program, but it is services only.  No inventory.
<img width="398" alt="image" src="https://github.com/abtassociates/eva/assets/142535880/86953ee4-47e6-476e-ae33-c893872a5a08">

135 | SMC-NYA-RRH-Emergency Solutions Grant-ESG | No Inventory Records | Error

</body>

</html>

**Comment by alex-silverman** [comment]
This issue has been fixed in Eva! Closing. If you're still experiencing this issue, please feel free to re-open or start a new issue.

**Comment by alapatra** [comment]
I just want to note I was experiencing this issue and am happy to share it has been resolved on our recent exports!
