### ISSUE TITLE
Data not collected

### ISSUE THREAD

**Issue by cyounggit** [abtassociates/eva#477]
**Is your feature request related to a problem? Please describe.**
There are some data checks where the error issue is referenced as a data point that is missing.  However when you check the data point in HMIS it shows as "Data Not Collected" (DNC), which evidently EVA interprets as "missing".  This creates a problem because the same data points that have already been reviewed for quality keep coming up, which is a waste of time because the agency has already determined the data cannot be collected.  It can be of benefit for an agency to know how frequent "DNC" is being utilized for a given data point, but they don't have to keep re-checking multiple times the same client enrollment it to see if the data can actually be collected/corrected.

**Describe the solution you'd like**
Can the results in EVA show "Data Not Collected" intstead of "Missing [. . .]"? 

**Describe alternatives you've considered**
The only alternative I know is to track a given enrollment as having been checked, and then cross-reference current EVA results with prior EVA results to flag those "missing" data points as having already been checked.

**Additional context**

**Comment by kiadso** [comment]
Hi @cyounggit,

Thank you for describing the issue. We will be addressing this in an upcoming update. It may be a few weeks, but it is in the queue!

Thanks again-

**Comment by kiadso** [comment]
Hi @cyounggit,
Thank you for bringing this issue to light. We did address it in the current update of Eva. You can review the summary of how we went about it in the Changelog as well:

>- Updated how 'Data not collected' is handled when Eva assesses data quality. Eva now classifies data elements marked in the export as 'Data not collected' as a Warning instead of as an Error, to align with Eva's Error and Warning definitions. This approach is aimed at helping HMIS end users focus on correcting fixable issues without changing accurate information. The Warning is meant to remind users to verify if the data might still be collected or if the data exists elsewhere, such as in the client's file. If 'Data not collected' is the correct value, users should leave the value as-is in HMIS. Issues that should be fixed in HMIS are categorized as Errors.
>- Removed logic that looks for nulls in specific data elements when Eva assesses data quality. For the Race/Ethnicity, Gender, Veteran Status, Disabling Condition, Name Data Quality, DOB Data Quality, SSN Data Quality, and Destination data elements, the HMIS CSV export does not distinguish between nulls and the value 'Data not collected.' The issues removed are: Missing Name Data Quality, Missing DOB Data Quality, Missing SSN Data Quality, Missing Gender, Missing Veteran Status, Missing Disabling Condition, and Missing Destination. These are now flagged as Warnings and described as 'Unknown Gender,' 'Unknown Veteran Status,' etc.

Thank you for your patience,
Eva dev team
