### ISSUE TITLE
Add EnrollID

### ISSUE THREAD

**Issue by shsdrc** [abtassociates/eva#482]
Would it be possible to add the EnrollID into the exports? This would be really useful for using the EVA data within other workbooks we use to manage our data!

**Comment by alyssandrichik** [comment]
@shsdrc Thanks for sharing this suggestion! We have added it to our backlog and will keep you updated on when we implement the change.

**Comment by LynnSharpe** [comment]
Hi,
I would also love to see the EnrollID in the export. Right now, I have to do a lot of trickery to match the issues identified to the correct enrollment.

**Comment by LynnSharpe** [comment]
Thank you!
