### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by Derek-Ruhl-HF** [abtassociates/eva#495]
**Describe the bug**
When clicking the Download button for the fully DQ report, it seems there is an issue on the server and it will not download the file.  This was reported by another user in our CoC and tested by myself with the same results.

**To Reproduce**
1. After uploading a successful Export, go to Assess Data Quality (any of the 3 sections will reproduce this).
2. Click on Download to try to get the report.
4. See error.  It looks like it's trying to download, but it says there was an error and to try again (within the browser download).

**Expected behavior**
I would expect the Excel file to download.

**Screenshot**
![image](https://github.com/abtassociates/eva/assets/165914380/edb3b9c7-0c24-492e-88ab-d5a75c98a5c8)

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Browser: Microsoft Edge (Incognito) and Chrome.

**Additional Content**
I never had this issue before, but today I just noticed the Demo button at the top right.  If I don't clear my cache, the Demo button is a little weird looking and Eva seems to do a mixture of my file and the demo file.  I can download a file in that way, but it is not correct.  Once I use Incognito mode or a browser that I haven't used Eva on, it does this issue.

**Comment by alyssandrichik** [comment]
@Derek-Ruhl-HF - thanks for reaching out about this! We have a couple of follow-up questions.

1. Can you let me know the time frame of when you and other members of your team attempted to download the DQ report?
2. Can you still not download the DQ report?
3. Can you share the Eva URL you are using?

Thanks!

**Comment by alyssandrichik** [comment]
@Derek-Ruhl-HF - Additionally, if you could provide some screenshots of the situation you described in your comment in the additional content section, that would be incredibly helpful! Thank you!

**Comment by Derek-Ruhl-HF** [comment]
1.  We tried downloading the report multiple times between 7-8am Central Time 4/3/24.
2.  I'm still getting the same error when trying to download (~1:48pm 4/3/24).
3.  https://hmis.abtsites.com/eva/

Here are results I'm getting after uploading my CSV (none of these programs are ours and seem to be Demo data.  The Demo button is set to Off.  The time frame is still what my CSV was run for.  Earlier today I believe the time frame was showing 10/1/2023 - 3/31/24, which was not anywhere close to what my CSV is.  That was why I originally brought up the Demo data interfering.  I hadn't seen actual data from the Demo until now when I went to get new screenshots.
![Demo Off Results](https://github.com/abtassociates/eva/assets/165914380/1909d0f4-252e-4a97-882f-8448e25c1eb6)

Here is the Demo button when I'm not using Incognito mode (I have not cleared my cache)
![Demo Button](https://github.com/abtassociates/eva/assets/165914380/3d048be4-849f-4fef-ac85-77eeafc712be)

**Comment by Derek-Ruhl-HF** [comment]
The date range for the CSV is 2/1/24 - 2/29/24.  I'm not sure where these org names are coming from, as none of them are in my export.  More concerning however, I just uploaded the exact same CSV and got completely different org names (still not my own) that look like legitimate org names from California.  I know Eva is not meant to store any data and is touted as being secure for that reason and others, but this does make me concerned about whether the numbers for these real orgs are legitimate or not (not that I can do much with that information).  I know I'm not seeing any PII in Eva or in the repot if I could download it, but I'm very curious how I'm getting information from what I can only assume is another user.

CoC Code: TX-600.

The Demo mode button seems like more of a caching issue than anything, so I'm not too concerned about it.  Based on my tests, I'd assume once I clear my cache in Edge (where I've solely used Eva before today), it will resolve itself.

**Comment by alyssandrichik** [comment]
@Derek-Ruhl-HF Thanks again for bringing this issue to our attention! As of this morning, Eva is live again with a fix to the download button. Please retry downloading the DQ report from Eva and let us know if you encounter any issues.
 
Additionally, demo mode is temporarily deactivated but will be available again in the near future after we finalize some updates.

**Comment by Derek-Ruhl-HF** [comment]
The download button is working just fine now, thank you!  Also, any other issues I was seeing with data not matching is resolved too.
