### ISSUE TITLE
Unable to access EVA

### ISSUE THREAD

**Issue by KGreenmv** [abtassociates/eva#504]
Hello,

EVA was recently down for maintenance and I am still unable to open the website. I am not sure if it is still down for maintenance. When I go to open the website, it gives me, "The application failed to start. The application exited during initialization."

**Comment by alex-silverman** [comment]
Hello,

Eva is still under maintenance at the moment. Thank you for bringing this to our attention. We will work on making the site's display message more clear.

Alex

**Comment by KGreenmv** [comment]
Thank you for getting back to me so quickly! Do you happen to have a timeline of when it will be back up?
