### ISSUE TITLE
Non-Participating Program Zero Utilization Warning

### ISSUE THREAD

**Issue by entomacy** [abtassociates/eva#522]
Some of our programs that were HMIS participating in the past, but are not and were not HMIS participating during the reporting date range are showing a Zero Utilization warning in the PDDE Checker. For example, one of our programs was participating 7/1/2020 to 4/5/2023, and non-participating as of 04/06/2023, but is currently appearing with this warning. The CSV export reporting range is 10/1/23 to 6/4/24.

**Comment by alyssandrichik** [comment]
Hi @entomacy, 

Thank you for reaching out about this! The Eva Team investigated this bug and agreed that we need to fix this. We have added it to our to-do list and will update you when it is implemented. We hope to get to it soon. 

Best,
Eva Team
