### ISSUE TITLE
Structure Analysis Detail file will not open upon download

### ISSUE THREAD

**Issue by candiceh214** [abtassociates/eva#526]
Structure Analysis Detail file will not open upon download
We are a vendor working with a community who is getting flagged for High Priority items for nulls or incorrect data type and for impermissible characters.  Both the CoC and the vendor have attempted to view the file after an upload attempt.  The download button is clicked and a file does download.  However, upon attempting to open the file the following message displays "We found a problem with some content in "xx file".  Do you want us to try to recover..."  No recovery is possible - the file appears blank.

We would like to work with the CoC to resolve the issues in our export but we need to understand the issues.  We have the file if needed.

Windows 10* 64-bit 
Firefox
Attempted again approx 10:45 central.

**Comment by kiadso** [comment]
Hi @candiceh214 !
So sorry for the delayed response.
Can you send a screenshot of what the message says? Also, I'm curious if they can run it again without some providers to see if we can narrow down where the impermissible character or incorrect data type is coming from? Let's have a call this week to see what we can figure out! 
Genelle

**Comment by kiadso** [comment]
Update: Candice reports that WellSky figured out where the impermissible character was and resolved the issue on their side. It was an apostrophe from a Windows character set.
