### ISSUE TITLE
HH Members Added Later

### ISSUE THREAD

**Issue by fbradford7** [abtassociates/eva#563]
**Is your feature request related to a problem? Please describe.**
Eva flags for Invalid Move-In Dates for household members who join the household after the Head of Household has entered the project. This is typically for children being born into the project or significant other moving in. It flags these situations both when the Housing Move-In Date for the late joiner is entered into the entry and when the late joiner's Housing Move-In Date is entered into an interim update.

**Describe the solution you'd like**
I would like it to not flag one of the situations so I kow which guidance to provide for staff.

**Describe alternatives you've considered**
I thought entering it into an interim update would solve this but it did not.

**Additional context**

**Comment by kiadso** [comment]
Hi @fbradford7,
Can you share an example of what you're seeing? If Client A has an RRH enrollment that goes from February 1, 2024 to April 30, 2024 and has a Move-In Date of March 14, 2024, and Client B is their infant who was born April 2, 2024, then Client B should have an EntryDate and Move-In Date of April 2, 2024 and ExitDate of April 30, 2024. If this is the data that is landing in your CSV Export, then Client B should not be flagged for an Invalid Move-In Date. If the scenario I described is the way you have entered the data into your HMIS but you are still seeing Eva flagging it, please contact your vendor so they can help you review your CSV Export to be sure your Move-In Dates are landing correctly in the export. You can also check it yourself using a text editor to find the enrollment in question to see what may be happening, but if you see unexpected values there, please reach out to your vendor.

Eva only checks that your Move-In Dates fall between your EntryDate and ExitDates. (You can see this code here: https://github.com/abtassociates/eva/blob/2514846bd9ba7e34a81f6820e899a1bbc5e79140/05_DataQuality.R#L1265)

Let us know if you are finding a problem with the way Eva is reading the export, and you feel like your export is correct.

Thank you
- Eva Dev team

**Comment by kiadso** [comment]
Hi @fbradford7,
I'm going to go ahead and close this Issue, but if you rerun your export, reupload to Eva, and are still seeing the same issue, please let us know!
Thank you-
Eva dev team
