### ISSUE TITLE
Missing household id flagged as too many heads of household

### ISSUE THREAD

**Issue by kheatwoleHRHA** [abtassociates/eva#580]
EVA is flagging hundreds of clients as having "too many heads of household," and this high-priority error persists even after the "relationship to head of household" field is corrected and a new hashed csv is exported and uploaded. 

I'm not sure, but I think the problem is that several of our providers did not follow HMIS protocol and did not associate individuals with a "single adult" household type before enrolling them in projects, so the entry/exit was not associated with a household in HMIS upon creation. Even if the "relationship to head of household" is correct and it is a single person with a "self" relationship, they are still being flagged as having too many heads of household.

1. will this lack of original association be a problem in the LSA, or is it an EVA quirk? (We did not have these shows up as issues with LSA last year, so I am guessing not as long as the relationship question is completed, but I want to be sure).
2. Can a new flag be developed in EVA to differentiate these types of household errors (where it was not originally associated) as distinct from having too many heads of household? 

Desktop
 - Operating System: Windows 11
 - Browser: Chrome

**Comment by kiadso** [comment]
Hi @kheatwoleHRHA,
I'm going to go ahead and close this Issue, but if you rerun your export and reupload to Eva and are still seeing the same problem, please let us know!
Thank you,
Eva dev team
