### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by vaisreenivasan** [abtassociates/eva#581]
Hello,

We are using EVA to address duplicate entries. It has been useful, but lately we are seeing a lot of entries that are not showing on the report. Is there a way to resolve this issue so that we can have all entries reported so that we can address them accordingly? Thank you.

**Comment by kiadso** [comment]
Hi @vaisreenivasan ,

Are you saying that previously Eva was picking up some duplicate entries and now it isn't? Or it's doing the same thing as always but you're asking for more broadly defined Duplicate Entries?

Eva currently looks for any instances where a client has more than one enrollment that share the same ProjectID and EntryDate.

Can you give some examples of the types of entries you are wanting to be counted?

Thanks for the clarification!
-Eva Dev team

**Comment by kiadso** [comment]
Ok, thanks for clarifying! What are the project types enrollments where you're seeing this?

Thanks-

**Comment by vaisreenivasan** [comment]
Mostly coordinated entry projects.

**Comment by kiadso** [comment]
Hi @vaisreenivasan,

Could you check that this is still an issue? We just released an update that may or may not have fixed the issue.

Thank you!

**Comment by alyssandrichik** [comment]
Hi @vaisreenivasan 

I am checking in again. Is this still an issue for you? Let us know!

**Comment by vaisreenivasan** [comment]
Hi,

Sorry for the delayed response. No, it is not an issue anymore. Thank you very much for your help.


Vaidehi Sreenivasan (Vai), M.P.A.
(she/her)
HMIS Data Quality and Monitoring Coordinator
Office of Homeless Services
***@***.******@***.***>
***@***.***
