### ISSUE TITLE
Incorrectly evaluating a Single DV Project Upload

### ISSUE THREAD

**Issue by TinoPazHSN** [abtassociates/eva#596]
I was testing how EVA would handle a DV project (set up parameters include:  Target Population = "Survivors of Domestic Violence" as well as Participation Status = "Comparable Database Participating.")

The project does not include any client or enrollment details (it is set up as a non-HMIS participating project that is prohibited from data entry and included in our system exclusively for HIC reports).

I still ran the CSV Export from our HMIS system with the Hash PII option ON (checked) to see if the EVA File Structure Analysis would find any issues with the project setup.

However, the file wasn't accepted with this message, "You uploaded an unhashed data set."  I have doubled-checked the CSV Export settings used (to make sure the Hash PII option was turned on) but still getting the same message.

The file upload occurred on 9/19/2024 around 5:10pm Eastern.

**Expected behavior**
I was expecting the file to be accepted as valid and show any issues the File Structure Analysis found or show nothing if no issues were encountered.

**Screenshots**
<img width="306" alt="Eva Message" src="https://github.com/user-attachments/assets/56f6f099-8607-408c-a0dd-e7d0c5774a5e">

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Browser: Microsoft Edge
 - HMIS: Eccovia ClientTrack

Agustin "Tino" Paz
Homeless Services Network of Central Florida

**Comment by kiadso** [comment]
Hi @TinoPazHSN 

If you open the Export.csv file in your export and look at the HashStatus, is it a 4?

Thank you, 
Eva dev team

**Comment by TinoPazHSN** [comment]
Yes, the HashStatus = 4.

**Comment by kiadso** [comment]
Hi @TinoPazHSN 
Thanks for checking that. If you open up the Client.csv on your local computer and look at the FirstName column, does it look hashed? Like are all the values the same length like this? 
![image](https://github.com/user-attachments/assets/140d9e71-2cbd-409f-ac5b-a6294c752a33)

**Comment by TinoPazHSN** [comment]
As mentioned initially, this is a DV project and DOESN'T enter client/enrollment data in our HMIS, so there aren't any clients.  The ONLY reason we were even testing this project was primarily for the project structure analysis.

**Comment by kiadso** [comment]
Oh ok, Eva will not work with an empty Client.csv file. It's rejecting it because it's looking for evidence of hashed data in the Client.csv file and not finding any.

We should make that clearer in the popup message.

**Comment by TinoPazHSN** [comment]
Ok, that makes sense.  So, in general, we shouldn't try to submit projects without any client enrollments.

Yes, the popup message, for these situations, could be clearer.

Thanks!
