### ISSUE TITLE
Projects listed twice in EVA are resulting in false errors

### ISSUE THREAD

**Issue by kheatwoleHRHA** [abtassociates/eva#605]
Three projects that are each listed once in my CoC's hashed csv (correct in both the Project.csv and ProjectCoC.csv file, with 38 projects) are then showing up twice in the View Client Counts > Select Project drop down menu (total of 41 projects -- see attached screenshot). Furthermore, all of the clients in these projects are showing up as having duplicate entries and too many heads of household in the data quality tabs. If I run a hashed-csv on each of these three projects individually, these errors do not appear. If I run a hashed-csv on these three projects together, they are doubled again. 

In all hashed-csv files, the projects are only listed once in our vendor's Project.csv file and I do not see any commonalities among them (different project types, providers, etc) that would be causing them to be duplicated in EVA.

**Comment by kiadso** [comment]
Hi @kheatwoleHRHA ,
Thank you for reporting this. We suspect this will be fixed in Monday's update, but I'd like to be certain. Can you check your HMISParticipating.csv file to see if that project has 2 records? If so, it should be fixed very soon! If not, we'll need to investigate further.

Thank you,
Eva dev team

**Comment by kiadso** [comment]
Hi @kheatwoleHRHA,

Could you try uploading again to see if you're still getting the same problem? It should be fixed now!

Cheers,
Eva dev team

**Comment by kiadso** [comment]
Closing this, please reopen if you find this to still be a problem! Thank you!

**Comment by kheatwoleHRHA** [comment]
Yes, that fixed it – thank you!

Kaitlin


--
Kaitlin Heatwole (she/her)
HMIS Administrator
Western Virginia Continuum of Care
***@***.***
540-209-1698
