### ISSUE TITLE
Project Type Filters, both System & Organization Levels

### ISSUE THREAD

**Issue by TinoPazHSN** [abtassociates/eva#611]
**Describe the solution you'd like**
Ideally, I there would be Project Type filter available from either Settings, System-level or Organization-level views.

**Describe alternatives you've considered**
I have started to group my CSV Exports by Project Type and/or Organization.

Thank you for your consideration.

**Comment by kiadso** [comment]
Hi @TinoPazHSN,
Can you describe how this would improve your data quality monitoring workflow so we can understand a little more? 
Thank you for clarifying,
Eva dev team

**Comment by kiadso** [comment]
Hi @TinoPazHSN,
We're going to close this one for now, but if you would like to provide more context around this, we will be happy to re-open it and consider making this change.
Thank you,
Eva dev team
