### ISSUE TITLE
Eva Crashed  - Too Many Users try again later

### ISSUE THREAD

**Issue by kaitlit** [abtassociates/eva#613]
**Describe the bug**
I'm with an HMIS lead and we received this message from a user on 9/27/24 at 2:29pm: "for the last 3 days, every time I tried to sign in I got the message "To Many Users try again later". Today I was able to get in and attempted to upload the HMIS CSV Export Zip file according to instructions. I got the following message:"
![image](https://github.com/user-attachments/assets/84084980-3ff5-4acf-b8d1-5c788c21292d)

**To Reproduce**
I think just try to upload behavior

**Expected behavior**
Analysis of data file

**Screenshots**
See above for error message

**Desktop (please complete the following information):**
Note sure - this was a user message

**Additional context**
n/a

**Comment by alex-silverman** [comment]
Hi @kaitlit,

Thank you for submitting this issue. We have determined that the reason you received the "Too many users" message was because our server was limiting the number of simultaneous users to 100, by default. We have increased that limit to avoid the issue in the future.

Are you still experiencing the other crash message?

**Comment by KingsUnitedWay** [comment]
I have been getting the same crash message all day today.  Is there a fix?

**Comment by rgibson111** [comment]
This one happened to 
![Screenshot 2024-10-08 140314](https://github.com/user-attachments/assets/85243895-aa83-4391-9a4a-fd32e83f1627)
me today. 10/8/2024

**Comment by kaitlit** [comment]
Hi - I'm re-opening this as I just tried to log in and got a white page with text reading: 
"An error has occurred
The application failed to start.

The application exited during initialization."

This is 10/10/24, 11:30am central, Windows computer, Edge browser.

(Side note - I started to look at the new performance measures and they look very helpful!)

Thank you!

**Comment by kiadso** [comment]
Hi @kaitlit,
Is this still happening?
We just noticed this comment!
Thank you!
Eva dev team

**Comment by kaitlit** [comment]
Not that I'm aware of - this was the most recent notice we've had of this issue. Thanks for following up!
