### ISSUE TITLE
Invalid Move-In Date Errors

### ISSUE THREAD

**Issue by klobdell209** [abtassociates/eva#615]
Hello, 

Our Team has noticed that the EVA export is populating errors for clients with a move-in date on the same day as their project entry. However, when looking at the FY 2024 HMIS Data Standards Manual, it states that the move-in date can be the same as the client's project enrollment date. See the attachment for more details. Let us know if there are further questions. 
![github](https://github.com/user-attachments/assets/13752686-81be-4a13-9532-6b589f90e697)
[github issue eva.docx](https://github.com/user-attachments/files/17194311/github.issue.eva.docx)

Thank you!

**Comment by kiadso** [comment]
Hi @klobdell209,

Thank you for raising this issue. We will work on correcting as soon as possible!

Thank you,
Eva dev team

**Comment by kiadso** [comment]
Hi @klobdell209,

This should be fixed now! Thank you so much for reporting it.

Eva dev team
