### ISSUE TITLE
Too Many Users

### ISSUE THREAD

**Issue by rgibson111** [abtassociates/eva#629]
I just used EVA yesterday with no issue, but now I can't get on it says:
"Sorry, but this application has exceeded its quota of concurrent users. Please try again later."

See attached Screenshot:
![Screenshot 2024-10-08 140314](https://github.com/user-attachments/assets/cfe53841-a7b2-4394-868b-8e6926ba9d23)

I did restart my browser which is Chrome on my HP Laptop.

Thank you!

**Comment by kiadso** [comment]
Hi @rgibson111,
Thank you so much for reporting this. We think this has been addressed. If you experience this issue again, please enter a new Issue!

Eva dev team
