### ISSUE TITLE
Eva has crashed

### ISSUE THREAD

**Issue by bcemswilerbucks** [abtassociates/eva#632]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB (HASHED OR NOT)**
**DO NOT UPLOAD YOUR EXPORT TO GITHUB (HASHED OR NOT)**
**DO NOT UPLOAD YOUR EXPORT TO GITHUB (HASHED OR NOT)**
I have not uploaded an export. 

**Describe the bug**
Eva crashed when hashed CSV is uploaded

**To Reproduce**
Export hashed CSV from ClientTrack HMIS
Upload zip file to EVA
Error message is given

I have received the message that EVA has crashed after adjusting local settings and after not adjusting anything and immediately doing the upload. I have tried clearing my caches.

The file is a hashed CSV from 10/9/2023 to 10/9/2024 for 4 street outreach type projects. 
File last attempted upload to EVA around 8:40AM on 10/10/2024.

**Expected behavior**
I expect EVA to accept the file and begin analysis

**Screenshots**
![image](https://github.com/user-attachments/assets/c42389d3-933a-41f9-871d-8032a257e560)

**Desktop (please complete the following information):**
 - Operating System: Windows 10 64 bit
 - Browser: Chrome

**Additional context**

**Comment by zabalad** [comment]
Hi @bcemswilerbucks, this issue has been resolved. Please try accessing Eva and let us know if you are still experiencing a problem.

**Comment by bcemswilerbucks** [comment]
I am still receiving the same error: 
![image](https://github.com/user-attachments/assets/83b27294-be77-4784-ac59-69c544dfe434)

**Comment by kiadso** [comment]
Hi @bcemswilerbucks,
We apologize for closing the wrong issue, and thank you for responding back! Can you email me at genelle dot denzin at abtglobal dot com?
Thank you!

**Comment by bcemswilerbucks** [comment]
Good afternoon,

The upload was a single project type of street outreach that had 4 projects that crashed. I have not attempted to upload any other reports recently. Earlier this year I ran a full system report of every project type for a 12 month period and did not experience any crashes.

Please let me know what other information you may need.

Thanks,


Brittany C. Emswiler (she/her)

Project Administrator, Data and Performance | County of Bucks

1260 Almshouse Road | Doylestown, PA 18901

215-345-3831 Office | ***@***.******@***.***>

Schedule a Meeting with ***@***.***?anonymous&ep=plink>



________________________________

**Comment by alex-silverman** [comment]
hi @bcemswilerbucks ,

Would you be willing and able to try re-uploading that same file that crashed to a temporary dev site here: https://hmis-stage.abtsites.com/eva-dev2?

This will help me try and locate the source of the problem.

Alex

**Comment by alex-silverman** [comment]
My mistake, Brittany. I just made a quick update. Can you try once more when you have a moment?

**Comment by bcemswilerbucks** [comment]
Good afternoon,

EVA is still crashing.

[cid:e669ee92-441d-456e-99a5-8ed6eed2702a]

I did upload a csv to EVA earlier today that was for all projects since this date last year. It uploaded with no issues.


Brittany C. Emswiler (she/her)

Project Administrator, Data and Performance | County of Bucks

1260 Almshouse Road | Doylestown, PA 18901

215-345-3831 Office | ***@***.******@***.***>

Schedule a Meeting with ***@***.***?anonymous&ep=plink>



________________________________

**Comment by bcemswilerbucks** [comment]
Good afternoon,

I opened in a new tab, held down shift and refreshed, and then hit F5 to clear the caches. It crashed as expected. Please let me know if it worked this time.

Thanks,


Brittany C. Emswiler (she/her)

Project Administrator, Data and Performance | County of Bucks

1260 Almshouse Road | Doylestown, PA 18901

215-345-3831 Office | ***@***.******@***.***>

Schedule a Meeting with ***@***.***?anonymous&ep=plink>



________________________________

**Comment by alex-silverman** [comment]
It did. This was helpful. I have a good idea of where the code is going wrong and possibly why. I will follow up when I have more info or need another upload. Thanks so much!

**Comment by alex-silverman** [comment]
So just to confirm, did you test on the hmis-stage site linked above? If so, did it work or did it still crash? If it still crashed, I'll need to continue digging into this.

It's definitely surprising that the files uploaded successfully in Eva live, as I have consistently been able to reproduce the crash when I include # symbols in the Funder.csv file.

**Comment by bcemswilerbucks** [comment]
Good morning,

I think I figured it out? It was crashing because the first row of column E started with a #. I reordered column E and re-saved the funder file. The hmis-stage site didn't work for me anymore so I tested it in Eva live and it uploaded successfully.

Original file - crashed in Eva live and crashed on the hmis-stage site that you linked. It has # at the beginning of some grants in the funder.csv file, and it happened to have one on the very first row of data.
Screenshot of failed upload GrantID column
[cid:7ad618b9-7341-47c5-b960-799261d5456b]
I reordered it and it uploaded successfully in EVA live, but I am now getting a structure analysis error, probably because I re-saved the file.  Screenshot of reordered column that successfully uploaded to EVA live but now gets a structure file issue.
[cid:df6ab6f7-60d2-401e-a5f5-8697603f21b9]


Current file - uploaded successfully in Eva live. It has # at the beginning of some grants in the funder.csv file, but not the very first row of data.
Screenshot of successful upload GrantID column

[cid:dc7a5571-68f8-4545-84c0-50aeefc1c1fe]




Brittany C. Emswiler (she/her)

Project Administrator, Data and Performance | County of Bucks

1260 Almshouse Road | Doylestown, PA 18901

215-345-3831 Office | ***@***.******@***.***>

Schedule a Meeting with ***@***.***?anonymous&ep=plink>



________________________________

**Comment by alex-silverman** [comment]
Hi Brittany,

Yes, that is exactly the problem! A # symbol in the first row of any csv file will cause Eva to crash. I pushed a fix to the original [hmis-stage site](https://hmis-stage.abtsites.com/eva-dev) (not the one I gave you in this thread) so if you're still experiencing the issue there, is it the same crashing pop-up as before or something else? I just want to make sure that the fix I made actually works for more than just me and that other user.

Alex

**Comment by bcemswilerbucks** [comment]
This is the error I'm getting now:

[cid:6908fcc2-31b3-486a-9f1e-b36e084de801]

And I'm 99% sure it is because I manually edited the file to test the reordering of column E. I don't know that I have the original unfortunately. I forgot to save a copy when I was testing. But I think the issue has been resolved.



Brittany C. Emswiler (she/her)

Project Administrator, Data and Performance | County of Bucks

1260 Almshouse Road | Doylestown, PA 18901

215-345-3831 Office | ***@***.******@***.***>

Schedule a Meeting with ***@***.***?anonymous&ep=plink>



________________________________

**Comment by alex-silverman** [comment]
Unfortunately, I'm unable to view those screenshots. Any way you can email me the screenshot at Alex.Silverman@abtglobal.com?

Regardless, I'm glad the issue has been resolved for you. We will push a fix to Eva shortly.

**Comment by alex-silverman** [comment]
We have pushed the hotfix for this in Eva, so I am closing this issue. Please submit a new issue if you continue having this or any other issue!
