### ISSUE TITLE
Error Has Occured

### ISSUE THREAD

**Issue by rgibson111** [abtassociates/eva#633]
Eva won't start. 

![Screenshot 2024-10-10 123615](https://github.com/user-attachments/assets/66b70b51-5639-4fa2-9db9-672458a53ac4)

**Comment by alex-silverman** [comment]
Hi Rachael. We are aware of this issue and working hard to fix it. We will respond here as soon as the issue is resolved.

**Comment by zabalad** [comment]
Hi @rgibson111, this issue has been resolved. Please try accessing Eva and let us know if you are still experiencing a problem.

**Comment by rgibson111** [comment]
It's working, Thank you!
