### ISSUE TITLE
Returned from Permanent and Re-engaged from Non-permanent shows 0

### ISSUE THREAD

**Issue by ksexton11** [abtassociates/eva#634]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB (HASHED OR NOT)**

**Describe the bug**
When uploading our system wide data which includes SO, ES, TH, RRH, PSH and SSO project types, we would expect to see some returns showing on the System flow chart on the System Performance overview feature in Eva. It shows zero for both the returned from Permanent and the re-engaged from non-permanent. 

**To Reproduce**
1. Go to '...'Eva and upload Hashed HMIS CSV
2. Click on '....'System Performance Overview
3. Scroll down to '....'System Flow
4. See error: showing 0 on Returned from Permanent and 0 on re-engaged from non-permanent

**Expected behavior**
We expected to see some returns (a higher number than 0) here, since we do indeed have returns on our system wide data

**Screenshots**
will attach screenshot

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Windows 10* 64-bit
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)
 - Google Chrome

**Smartphone (please complete the following information):**
 - n/a
[github screenshot Eva.docx](https://github.com/user-attachments/files/17333298/github.screenshot.Eva.docx)

**Additional context**
This was ran on CY 2023

**Comment by kiadso** [comment]
Hi @ksexton11!
Thank you for the thorough description of the problem. Try running and uploading an export on a three-year date range and then you should see some results there. Let us know if that doesn't work!
Thanks,
Eva dev team
