### ISSUE TITLE
EVA Site will not Load

### ISSUE THREAD

**Issue by RbannermanLICH** [abtassociates/eva#636]
The Eva site will not load.  I started on site 'https://www.hudexchange.info/programs/hmis/eva/' and clicked on Access Eva button and received the error message attached

Thanks Roxzelle Bannerman-Martin

![EVA will NOT load](https://github.com/user-attachments/assets/27882f7d-900f-45f2-88df-b10a3a488f2f)
**DO NOT UPLOAD YOUR EXPORT TO GITHUB (HASHED OR NOT)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zabalad** [comment]
HI @RbannermanLICH , thanks for bringing this to our attention, we are looking into the problem now. We appreciate your patience while we work to resolve this.

**Comment by zabalad** [comment]
@RbannermanLICH the issue should be fixed now, but please let us know if you are still experiencing issues.

**Comment by RbannermanLICH** [comment]
The EVA website is not loading again today.  Same message as previously reported.  Please review and advise

Thanks Roxzelle
