### ISSUE TITLE
EVA System Performance System Demographic Chart still has suppressed values after download

### ISSUE THREAD

**Issue by ksobers10** [abtassociates/eva#637]
The chart has suppressed values in the visualization.  However, it states that when its downloaded the suppressed values will show. I downloaded my visualization and the suppressed values were still showing as ***.

To replicate the issue:
1) Upload hashed csv file
2) Go to System Performance tab
3) Choose System Demographics chart

**Comment by kiadso** [comment]
Hi @ksobers10,
After you choose the System Demographics chart, how are you downloading the data? If you click the Data Download button, it should give you the unsuppressed data in an Excel file. If you download the image (the Image Download button), you will get the image as it is (suppressed.)
Let us know if you are not getting the unsuppressed data in the Excel file!
Thank you!
Eva dev team

**Comment by kiadso** [comment]
Hi Keli! :)

I will escalate this and see where it lands!

Thank you for submitting the question!
Genelle

**Comment by ksobers10** [comment]
Thanks for your response. I understand the meaning behind why you are suppressing the data, however, can you leave that security and protection up to us?  Can you possibly give us the option to suppress or unsuppress the data?  Then we can use that option that is best for us. Also, I know that we can use the Excel data to make our own custom charts, but I thought this was offered to help us and save time. It is not helping as much if we have to do it ourself.  Furthermore, I tried to do that and my charts don't look nearly as good as yours.  Please take this request under consideration.

**Comment by vlopez0603** [comment]
Thanks again for your feedback and suggestion, Keli. We will send this to HUD for their review. In the meantime, we'll close this ticket and reach back out to you if we get more information about a decision on this from HUD.
