### ISSUE TITLE
EVA Website is down

### ISSUE THREAD

**Issue by LCowan22** [abtassociates/eva#639]
**Describe the bug**
When attempting to access EVA to complete an upload, the page displays an error message that states either "This Page is not working" or "Website timed out, took too long". 

**To Reproduce**
1. https://hmis.abtsites.com/eva/

**Expected behavior**
To access EVA main page for uploads

**Screenshots**
![image](https://github.com/user-attachments/assets/b608921d-2bce-4572-85ef-1bf19fe6b346)

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Browser: Chrome and MS Edge

**Comment by zabalad** [comment]
Hi @LCowan22 , the issue should be fixed now. Please let us know if you are still experiencing issues. Thanks!
