### ISSUE TITLE
Receiving a Future Entry Date Warning

### ISSUE THREAD

**Issue by rgibson111** [abtassociates/eva#642]
Hi!

We have a future entry date warning appearing on our EVA results and upon opening a ticket with our vendor, they saw that everything looked correct in the system, so I wanted to open a ticket here in case it's a bug on EVA's end. 

Let me know if you need anymore information.

Thank you!

**Comment by alex-silverman** [comment]
Hi Rachael,

Sorry for the delay in responding here. Let me first clarify how this warning is determined:

1. If the enrollment's EntryDate is after it's DateCreated AND either

    1. the corresponding ProjectType is not a PSH one; or
    2. the corresponding ProjectType is PSH but EntryDate is on or after 10/1/2017 (the date that PSH projects started tracking distinct move-in dates).

If this is indeed a bug in Eva, then the flagged enrollment will NOT meet the above conditions. To confirm it does not, you can download Eva's Data Quality export for the relevant Organization, navigate to the Warnings tab, and locate the flagged enrollment. From there, you can confirm that (1) the ProjectType is not a PH one; or (2) it is, but the EntryDate is on or after 10/1/2017.

If neither is true, then let us know as Eva should not be flagging this enrollment as having a Future Entry Date.

If both are true, then note the EnrollmentID and EntryDate, open the Enrollment.csv file, find that EnrollmentID, and confirm that the DateCreated is prior to that EntryDate. If it's not, then it's indeed a false flag.

If all conditions are met, however, then Eva is correctly flagging this as a Future Entry Date warning. In this case, it may be that the vendor is looking at the wrong data or the data in the system somehow doesn't align with what is being exported.

Alex

**Comment by rgibson111** [comment]
Hi!

Thank you for this information. I will look into it and let you know. I have another Future Entry Date on another Agency so having the parameters will help in checking.

**Comment by kiadso** [comment]
Hi @rgibson111,

Let us know what you find- I will close this at the end of the day if we haven't heard back but if you do find that Eva is in error, please re-open this issue!

Thank you,
Eva dev team
