### ISSUE TITLE
Warning page not showing any information except Issue.

### ISSUE THREAD

**Issue by brenttdecarlo** [abtassociates/eva#644]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB (HASHED OR NOT)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brenttdecarlo** [comment]
Chrome, Windows 10

Full data spreadsheet

Organization Summary

Organization Name
Type
Enrollments
Issue
Warning
3
Days since Most Recent CLS Exceeds Local Settings
Warning
3
Long Stayers (Local Settings)

Warnings
Organization Name
Project ID
Project Name
Project Type
Issue
Personal ID
Enrollment ID
Household ID
Entry Date
Long Stayers (Local Settings)
Days since Most Recent CLS Exceeds Local Settings
Long Stayers (Local Settings)
Days since Most Recent CLS Exceeds Local Settings
Long Stayers (Local Settings)
Days since Most Recent CLS Exceeds Local Settings

***@***.***

IL-506 CoC Lead Administrator

CONFIDENTIALITY NOTICE: This email and any files or attachments transmitted with it are confidential and may be protected by legal privilege. This email is intended solely for the use of the individual or entity to whom this email is addressed. If you are not the intended recipient of this email, you are hereby notified that any use, dissemination, distribution or copying of this email is strictly prohibited. If you have received this email in error, please notify the sender immediately by email and delete this email from your system.

***@***.***

Email: ***@***.******@***.***>
54 N. Ottawa Street | Suite 300 | Joliet, IL 60432
[Logo, icon    Description automatically generated]<https://www.facebook.com/uwwill/>[Logo    Description automatically generated]<https://www.linkedin.com/company/united-way-of-will-county>[Icon    Description automatically generated]<https://www.instagram.com/uwwill/>https://uwwill.org/   | www.willcountycoc.com<http://www.willcountycoc.com/>

**Comment by kiadso** [comment]
hi @brenttdecarlo,

Can you add some information so we can better understand what's going on? We need to be able to reproduce what you're doing so we can experience the behavior on our side so that we can figure out maybe what is wrong.

When you go to Eva, what tabs and buttons are you clicking? When you do that, what do you see? When you see that, what tab are you on (or if you're in Excel when you're seeing this, then what download was it?) 

Does this happen with any file you upload or does it only happen if you upload a particular one with certain projects selected?

Whenever you upload this file, do you get any File Structure Analysis issues? If so, what are they?

Thank you,
Eva dev team

**Comment by brenttdecarlo** [comment]
Genelle,

Running this as we have in the past, downloading the system level data from the access data quality section.

Tabs are what you been given it can be an error, high priority or warning and it is with multiple agencies.

***@***.***

IL-506 CoC Lead Administrator

CONFIDENTIALITY NOTICE: This email and any files or attachments transmitted with it are confidential and may be protected by legal privilege. This email is intended solely for the use of the individual or entity to whom this email is addressed. If you are not the intended recipient of this email, you are hereby notified that any use, dissemination, distribution or copying of this email is strictly prohibited. If you have received this email in error, please notify the sender immediately by email and delete this email from your system.

***@***.***<https://willcountycoc.com/>

[A screenshot of a computer  Description automatically generated]<https://uwwill.org/spirit-of-giving/>

Email: ***@***.******@***.***>
54 N. Ottawa Street | Suite 300 | Joliet, IL 60432
[Logo, icon    Description automatically generated]<https://www.facebook.com/uwwill/>[Logo    Description automatically generated]<https://www.linkedin.com/company/united-way-of-will-county>[Icon    Description automatically generated]<https://www.instagram.com/uwwill/>https://uwwill.org/   | www.willcountycoc.com<http://www.willcountycoc.com/>

**Comment by kiadso** [comment]
Hi @brenttdecarlo 
We aren't seeing any screenshots on GitHub or in the email notifications we get. I'm having a hard time piecing together the issue but my best guess as to what you are experiencing is that somewhere, either in the app itself or in the system data quality download, you are seeing blank Project Names? And this is happening consistently with the same export you have used previously with the same exact parameters, and it used to display the Project Names but now it isn't. I am guessing you are running your export on your entire system and that this is happening for all projects? Is this accurate? If it is happening in the download only, what program are you using to open the file? If it's happening in the Eva app, can you list the steps you are taking?
I think a screenshot would really help us, but if you can't provide that, we can keep trying to understand where you are seeing this, maybe we can set up a call?
Thanks

**Comment by brenttdecarlo** [comment]
I am unaware of any hash download changes from the vendor. This condition did not exist until the last upgrade of EVA. The process to produce the results are unchanged. The data is compiled from a hash report in hmis. The zip file is introduce into the eva algorithms. The results are as you see.

What screen shots do you desire without causing any privacy issues?

***@***.***

IL-506 CoC Lead Administrator

CONFIDENTIALITY NOTICE: This email and any files or attachments transmitted with it are confidential and may be protected by legal privilege. This email is intended solely for the use of the individual or entity to whom this email is addressed. If you are not the intended recipient of this email, you are hereby notified that any use, dissemination, distribution or copying of this email is strictly prohibited. If you have received this email in error, please notify the sender immediately by email and delete this email from your system.

***@***.***<https://willcountycoc.com/>

[A screenshot of a computer  Description automatically generated]<https://uwwill.org/spirit-of-giving/>

Email: ***@***.******@***.***>
54 N. Ottawa Street | Suite 300 | Joliet, IL 60432
[Logo, icon    Description automatically generated]<https://www.facebook.com/uwwill/>[Logo    Description automatically generated]<https://www.linkedin.com/company/united-way-of-will-county>[Icon    Description automatically generated]<https://www.instagram.com/uwwill/>https://uwwill.org/   | www.willcountycoc.com<http://www.willcountycoc.com/>

**Comment by alex-silverman** [comment]
Hi @brenttdecarlo ,

I think this would be worth trying to schedule a call. Are you available today at all? I have availability beginning at 2pm EST. If you're available today or tomorrow, please email me at alex.silverman[at]abtglobal[dot]com. Otherwise, we can try and schedule a time for next week.

Alex

**Comment by brenttdecarlo** [comment]
This week is LSA time, next week need to schedule a time.

***@***.***

IL-506 CoC Lead Administrator

CONFIDENTIALITY NOTICE: This email and any files or attachments transmitted with it are confidential and may be protected by legal privilege. This email is intended solely for the use of the individual or entity to whom this email is addressed. If you are not the intended recipient of this email, you are hereby notified that any use, dissemination, distribution or copying of this email is strictly prohibited. If you have received this email in error, please notify the sender immediately by email and delete this email from your system.

***@***.***<https://willcountycoc.com/>

[A screenshot of a computer  Description automatically generated]<https://uwwill.org/spirit-of-giving/>

Email: ***@***.******@***.***>
54 N. Ottawa Street | Suite 300 | Joliet, IL 60432
[Logo, icon    Description automatically generated]<https://www.facebook.com/uwwill/>[Logo    Description automatically generated]<https://www.linkedin.com/company/united-way-of-will-county>[Icon    Description automatically generated]<https://www.instagram.com/uwwill/>https://uwwill.org/   | www.willcountycoc.com<http://www.willcountycoc.com/>

**Comment by alex-silverman** [comment]
Hi @brenttdecarlo - please reach via email out whenever you're ready, so we can schedule a call this week or next.

**Comment by zabalad** [comment]
We're closing this issue for now, but please reach out to schedule a call if you are continuing to experience this problem.
