### ISSUE TITLE
Integer vs string

### ISSUE THREAD

**Issue by malspaugh** [abtassociates/eva#81]
We have 3 errors indicating that a data type should be a string instead of an integer. These data *are* strings, they just happen to also be integers. e.g. our software version is "2022" and our UserIDs are "35"

In the   EmploymentEducation file, the UserID column should have a data type of string   but in this file, it is integer

In the   EmploymentEducation file, the ExportID column should have a data type of   string but in this file, it is integer

In the Export file,   the SoftwareVersion column should have a data type of string but in this   file, it is integer

**Comment by kiadso** [comment]
Hi Meradith,

Thanks for posting this! Exports should conform to the data types in the specs. This may mean that the data types must be explicitly assigned in your code so that whatever system you're using to build the csv's doesn't assign data types by guessing, based on the data that's in that column. For some of the columns, an incorrect data type can cause Eva to either show incorrect results or crash. 

You can check your csv output files for quotes or not-quotes by opening them in a text editor instead of Excel.

**Comment by malspaugh** [comment]
Hi Genelle,
I may not have been clear in my initial bug report. I think we are identifying the data as strings, but Eva still flagged them as errors because they were interpreted to be integers. Does this info below help?

Error list for reference, using “1” as the first line of an error:
***@***.***


1,2: A snapshot from our export file indicates both those columns (UserID = 3rd column from the end, ExportID = last column) are double-quoted as strings.  Coincidentally, our user IDs in our system are always integers even though they are quoted as though they are strings.  You will see that the ExportID is a GUID that cannot be interpreted as an integer.  So I am not sure why error #2 is occurring.
***@***.***

4: It is true that SoftwareVersion is a string in the CSV specs, but that does not preclude it being entirely numeric.  Our output does wrap the string in double quotes, even though it only contains numbers.
***@***.***



Meradith

**Comment by malspaugh** [comment]
Hi Genelle,
Sorry about that, yes, there were screenshots. I've reattached them here, hopefully I did it right!
![all errors](https://user-images.githubusercontent.com/64660649/208109647-e1dd15ad-825e-4bc9-a50d-523f1e565ec2.png)


![errors1-2](https://user-images.githubusercontent.com/64660649/208109651-ffd1859a-1fe3-4a04-8352-7a559cdef93a.png)
![no 4](https://user-images.githubusercontent.com/64660649/208109664-34072cf8-e764-4c5c-b7c9-2fd3e44ec750.png)

**Comment by kiadso** [comment]
ok thank you! this is so helpful!
