### ISSUE TITLE
InformationDate error for YouthEducationStatus

### ISSUE THREAD

**Issue by DANIELLEPHUMES** [abtassociates/eva#84]
Getting error in file structure analysis download that Nulls not allowed in this column | Error | The InformationDate column in the YouthEducationStatus file contains   nulls where they are not allowed.

The InformationDate is not null in the Hashed CSV that was uploaded.

**Comment by kiadso** [comment]
@DANIELLEPHUMES, we think we may know what the problem here is- can you let us know if the dates in your csv file for the InformationDate in the YouthEducationStatus csv are in ymd format or ymd hms format?

Thank you!

**Comment by kiadso** [comment]
Hi @DANIELLEPHUMES I'm closing this, please let us know if your issue wasn't resolved with today's updates. Thanks!
